#include "projectexport.h"

#include "codegen.h"
#include "databasesession.h"

#include <QDir>
#include <QFile>
#include <QFileInfo>
#include <QRegularExpression>
#include <QStandardPaths>
#include <QUrl>

// The Qivot files exported projects carry (core/qivot.qrc). The resource sits
// in a static library, so it's initialised by hand, outside any namespace.
static QString qivotFile(const QString &name)
{
    Q_INIT_RESOURCE(qivot);
    QFile f(QStringLiteral(":/qivot/") + name);
    // As checked out: CRLF on a Windows clone. Exported projects get LF.
    return f.open(QIODevice::ReadOnly) ? QString::fromUtf8(f.readAll()).remove(QLatin1Char('\r')) : QString();
}

namespace {

// Replace @KEY@ placeholders in a template.
QString fill(QString text, const QMap<QString, QString> &values)
{
    for (auto it = values.begin(); it != values.end(); ++it)
        text.replace(QLatin1Char('@') + it.key() + QLatin1Char('@'), it.value());
    return text;
}

QString cString(QString text)
{
    text.replace(QLatin1Char('\\'), QLatin1String("\\\\"));
    text.replace(QLatin1Char('"'), QLatin1String("\\\""));
    return QLatin1Char('"') + text + QLatin1Char('"');
}

// "My shop!" -> "My_shop_": usable as a CMake project and C++ name.
QString identifier(const QString &name)
{
    QString id;
    for (const QChar c : name)
        id += c.isLetterOrNumber() && c.unicode() < 128 ? c : QLatin1Char('_');
    if (id.isEmpty() || id.at(0).isDigit())
        id.prepend(QLatin1Char('P'));
    return id;
}

const char *CMakeTemplate = R"(# @NAME@: Qivot models for @SOURCE@, generated by Qivot Studio.
cmake_minimum_required(VERSION 3.21)
project(@IDENT@ LANGUAGES CXX)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_AUTOMOC ON)

# Qt 6, or Qt 5.15: whichever CMAKE_PREFIX_PATH points at.
find_package(QT NAMES Qt6 Qt5 REQUIRED COMPONENTS Core)
find_package(Qt${QT_VERSION_MAJOR} REQUIRED COMPONENTS Core Sql Test)

# Qivot, included as its single header (third_party/qivot): qivot.cpp
# compiles the implementation once, and everything else includes qivot.hpp.
add_library(qivot STATIC third_party/qivot/qivot.cpp third_party/qivot/qivot.hpp)
target_include_directories(qivot PUBLIC third_party/qivot)
target_link_libraries(qivot PUBLIC Qt${QT_VERSION_MAJOR}::Core Qt${QT_VERSION_MAJOR}::Sql)
# Qivot's model macros take offsetof() of the model classes, which is fine but
# makes GCC and Clang warn on every model.
if(CMAKE_CXX_COMPILER_ID MATCHES "Clang|GNU")
    target_compile_options(qivot PUBLIC -Wno-invalid-offsetof)
endif()

# The example program.
add_executable(@TARGET@ src/main.cpp src/models.h src/database.h)
target_link_libraries(@TARGET@ PRIVATE qivot)

# One test per model: it loads every row and follows the foreign keys.
enable_testing()
add_executable(tst_models tests/tst_models.cpp)
target_include_directories(tst_models PRIVATE src)
target_link_libraries(tst_models PRIVATE qivot Qt${QT_VERSION_MAJOR}::Test)
foreach(model
@MODELS@)
    add_test(NAME ${model} COMMAND tst_models ${model})
endforeach()
)";

const char *ReadmeTemplate = R"(# @NAME@

[Qivot](https://github.com/austinkottke/Qivot) models for every table in
@SOURCE@, generated by Qivot Studio: @COUNT@ models, an example program, and
a test per model.

| File | What's in it |
|------|--------------|
| `src/models.h` | One `QiModel` class per table |
| `src/database.h` | `openDatabase()`: connects to @SOURCE@ |
| `src/main.cpp` | The example: counts each model's rows and follows a foreign key |
| `tests/tst_models.cpp` | A test per model: every row loads, and its foreign keys find their rows |
| `third_party/qivot/` | Qivot itself, as its single header (MIT) |

## Build and test

Needs Qt 6 or Qt 5.15 and CMake 3.21+. Qivot comes with it, as its single
header in `third_party/qivot` (MIT; see the licence files there), so there's
nothing else to fetch.

```bash
cmake -S . -B build -DCMAKE_PREFIX_PATH=/path/to/Qt/6.8.3/macos
cmake --build build
ctest --test-dir build --output-on-failure
```

## Pointing it at a database

`openDatabase()` uses the database the project was generated from. These
environment variables change that:

@ENV@
)";

// (Q_OBJECT and the moc include are split so AutoMoc doesn't act on this file.)
const char *TestTemplate = R"(// One test per model: every row loads, and each foreign key finds its row.
// Run them all with ctest, or one model with: tst_models @FIRST@
#include <QtTest>
#include <QSqlError>
#include <QSqlQuery>

#include "database.h"
#include "models.h"

namespace {

constexpr qint64 MappedRows = 5000;   // rows read into a model; the rest are only counted
constexpr qint64 FollowedKeys = 25;   // rows whose foreign keys are followed

// A model's key: Qivot's built-in id, or its QiPrimary field.
template <typename T>
QVariant keyOf(T &model)
{
    QiModelMetaInfo *info = qiMetaInfo<T>();
    const QString key = info->primaryKeyName();
    return info->value(&model, key.isEmpty() ? QStringLiteral("id") : key);
}

// A foreign key must load the row it points at.
template <typename Key>
bool follows(Key &key)
{
    return key.get().isNull() || keyOf(key()).toLongLong() == key.get().toLongLong();
}

} // namespace

class TestModels : public QObject
{
    Q_)" "OBJECT" R"(

    QiConnection m_connection;

    // Reads T's whole table through Qivot. The row count must match COUNT(*),
    // and `each` checks the first MappedRows rows.
    template <typename T, typename Each>
    void loadsEveryRow(Each each)
    {
        QSqlQuery count;
        QVERIFY2(count.exec(QStringLiteral("SELECT COUNT(*) FROM ") + T::TableName()),
                 qPrintable(count.lastError().text()));
        QVERIFY(count.next());
        const qint64 expected = count.value(0).toLongLong();

        QiQuery<T> query;
        QVERIFY2(query.exec(), "Qivot's SELECT failed");
        qint64 rows = 0;
        while (query.next()) {
            if (rows < MappedRows) {
                T row;
                QVERIFY2(query.recordTo(row), qPrintable(QStringLiteral("row %1 didn't load").arg(rows + 1)));
                each(row, rows);
                if (QTest::currentTestFailed())
                    return;
            }
            ++rows;
        }
        QCOMPARE(rows, expected);
    }

private slots:
    void initTestCase() { QVERIFY(openDatabase(m_connection)); }
@SLOTS@};

QTEST_GUILESS_MAIN(TestModels)
#)" "include \"tst_models.moc\"\n";

const char *MainTemplate = R"(// @NAME@: a Qivot program over @SOURCE@.
// Prints how many rows each model sees@FOLLOWS@.
#include <QCoreApplication>
#include <QDebug>

#include "database.h"
#include "models.h"

int main(int argc, char *argv[])
{
    QCoreApplication app(argc, argv);
    QiConnection connection;
    if (!openDatabase(connection))
        return 1;

    qInfo().noquote() << "Rows per model:";
@COUNTS@@EXAMPLE@    return 0;
}
)";

QString databaseHeader(const QVariantMap &s)
{
    const QString type = s.value(QStringLiteral("type")).toString();
    QString body;
    if (type == QLatin1String("sqlite")) {
        body = fill(QStringLiteral(
            "    QSqlDatabase db = QSqlDatabase::addDatabase(QStringLiteral(\"QSQLITE\"));\n"
            "    db.setDatabaseName(qEnvironmentVariable(\"QIVOT_DB\", QStringLiteral(@PATH@)));\n"),
            { { QStringLiteral("PATH"), cString(s.value(QStringLiteral("path")).toString()) } });
    } else {
        const QString driver = s.value(QStringLiteral("driver")).toString();
        QMap<QString, QString> v = {
            { QStringLiteral("HOST"), cString(s.value(QStringLiteral("host")).toString()) },
            { QStringLiteral("PORT"), cString(s.value(QStringLiteral("port")).toString()) },
            { QStringLiteral("DB"), cString(s.value(QStringLiteral("database")).toString()) },
            { QStringLiteral("USER"), cString(s.value(QStringLiteral("user")).toString()) },
            { QStringLiteral("DRIVER"), cString(driver) },
            { QStringLiteral("ODBC"), cString(s.value(QStringLiteral("odbcDriver")).toString()) },
        };
        body = QStringLiteral(
            "    const QString host = qEnvironmentVariable(\"QIVOT_DB_HOST\", QStringLiteral(@HOST@));\n"
            "    const int port = qEnvironmentVariable(\"QIVOT_DB_PORT\", QStringLiteral(@PORT@)).toInt();\n"
            "    const QString name = qEnvironmentVariable(\"QIVOT_DB\", QStringLiteral(@DB@));\n"
            "    const QString user = qEnvironmentVariable(\"QIVOT_DB_USER\", QStringLiteral(@USER@));\n"
            "    const QString password = qEnvironmentVariable(\"QIVOT_DB_PASSWORD\");\n\n");
        if (driver == QLatin1String("QODBC")) {
            body += QStringLiteral(
                "    // ODBC takes one connection string; {braces} quote each value.\n"
                "    auto braced = [](QString v) { return QLatin1Char('{') + v.replace(QLatin1Char('}'), QLatin1String(\"}}\")) + QLatin1Char('}'); };\n"
                "    QSqlDatabase db = QSqlDatabase::addDatabase(QStringLiteral(\"QODBC\"));\n"
                "    db.setDatabaseName(QStringLiteral(\"Driver={%1};Server=%2,%3;Database=%4;Uid=%5;Pwd=%6;TrustServerCertificate=yes;\")\n"
                "                           .arg(QStringLiteral(@ODBC@), host).arg(port)\n"
                "                           .arg(braced(name), braced(user), braced(password)));\n");
        } else {
            if (driver == QLatin1String("QMYSQL") || driver == QLatin1String("QMARIADB"))
                body += QStringLiteral(
                    "    // Qt names its MySQL driver QMARIADB in some builds.\n"
                    "    const QString driver = QSqlDatabase::isDriverAvailable(QStringLiteral(\"QMYSQL\"))\n"
                    "                         ? QStringLiteral(\"QMYSQL\") : QStringLiteral(\"QMARIADB\");\n"
                    "    QSqlDatabase db = QSqlDatabase::addDatabase(driver);\n");
            else
                body += QStringLiteral("    QSqlDatabase db = QSqlDatabase::addDatabase(QStringLiteral(@DRIVER@));\n");
            body += QStringLiteral(
                "    db.setHostName(host);\n"
                "    db.setPort(port);\n"
                "    db.setDatabaseName(name);\n"
                "    db.setUserName(user);\n"
                "    db.setPassword(password);\n");
        }
        body = fill(body, v);
    }
    return QStringLiteral(
        "// Opens the database the project was generated from; see README.md to point it elsewhere.\n"
        "#ifndef DATABASE_H\n#define DATABASE_H\n\n"
        "#include <QDebug>\n#include <QSqlDatabase>\n#include <QSqlError>\n#include <qivot.hpp>\n\n"
        "/// Connects Qt to the database and opens a Qivot connection on it.\n"
        "inline bool openDatabase(QiConnection &connection)\n{\n")
        + body
        + QStringLiteral(
        "    if (!db.open()) {\n"
        "        qWarning().noquote() << \"Can't open the database:\" << db.lastError().text();\n"
        "        return false;\n"
        "    }\n"
        "    return connection.open(db);\n}\n\n#endif // DATABASE_H\n");
}

QString environmentTable(const QVariantMap &s)
{
    if (s.value(QStringLiteral("type")).toString() == QLatin1String("sqlite"))
        return QStringLiteral("| Variable | Default |\n|----------|---------|\n| `QIVOT_DB` | `%1` |\n")
            .arg(s.value(QStringLiteral("path")).toString());
    return QStringLiteral("| Variable | Default |\n|----------|---------|\n"
                          "| `QIVOT_DB_HOST` | `%1` |\n| `QIVOT_DB_PORT` | `%2` |\n| `QIVOT_DB` | `%3` |\n"
                          "| `QIVOT_DB_USER` | `%4` |\n| `QIVOT_DB_PASSWORD` | (none: it is never written to disk) |\n")
        .arg(s.value(QStringLiteral("host")).toString(), s.value(QStringLiteral("port")).toString(),
             s.value(QStringLiteral("database")).toString(), s.value(QStringLiteral("user")).toString());
}

// The example's second half: follow one foreign key, labelled by a text field on each side.
QString followExample(const QVector<CodeGen::Model> &models, QString *summary)
{
    auto textField = [](const CodeGen::Model &m) -> QString {
        for (const CodeGen::Field &f : m.fields)
            if (f.cppType == QLatin1String("QString") && f.target.isEmpty())
                return f.name;
        return QString();
    };
    for (const CodeGen::Model &m : models) {
        const QString label = textField(m);
        if (label.isEmpty())
            continue;
        for (const CodeGen::Field &f : m.fields) {
            if (f.target.isEmpty())
                continue;
            const CodeGen::Model *parent = nullptr;
            for (const CodeGen::Model &p : models)
                if (p.className == f.target)
                    parent = &p;
            const QString parentLabel = parent ? textField(*parent) : QString();
            if (parentLabel.isEmpty())
                continue;
            *summary = QStringLiteral(", then follows %1.%2 to %3").arg(m.className, f.name, f.target);
            return fill(QStringLiteral(
                "\n    // A QiForeignKey loads the row it points at the first time you use it.\n"
                "    qInfo().noquote() << \"\\n@CLASS@ -> @TARGET@:\";\n"
                "    QiList<@CLASS@> rows = @CLASS@::objects().limit(5).all();\n"
                "    for (int i = 0; i < rows.size(); ++i) {\n"
                "        @CLASS@ *row = rows.at(i);\n"
                "        qInfo().noquote() << \"  \" << row->@LABEL@.get().toString()\n"
                "                          << \"->\" << row->@FIELD@->@PLABEL@.get().toString();\n"
                "    }\n"),
                { { QStringLiteral("CLASS"), m.className }, { QStringLiteral("TARGET"), f.target },
                  { QStringLiteral("LABEL"), label }, { QStringLiteral("FIELD"), f.name },
                  { QStringLiteral("PLABEL"), parentLabel } });
        }
    }
    return QString();
}

} // namespace

ProjectExport::ProjectExport(QObject *parent)
    : QObject(parent)
    , m_directory(defaultDirectory())
{
}

void ProjectExport::setSession(DatabaseSession *session)
{
    if (session == m_session)
        return;
    if (m_session)
        disconnect(m_session, nullptr, this, nullptr);
    m_session = session;
    if (m_session)
        connect(m_session, &DatabaseSession::openChanged, this, [this] {
            emit sessionChanged();
            regenerate();
        });
    emit sessionChanged();
    regenerate();
}

void ProjectExport::setName(const QString &name)
{
    if (name == m_name)
        return;
    m_name = name;
    emit nameChanged();
    emit pathChanged();
    regenerate();
}

void ProjectExport::setDirectory(const QString &directory)
{
    QString dir = directory;
    if (dir.startsWith(QLatin1String("file:")))
        dir = QUrl(dir).toLocalFile();
    if (dir == m_directory)
        return;
    m_directory = dir;
    emit directoryChanged();
    emit pathChanged();
}

QString ProjectExport::projectPath() const
{
    return m_name.trimmed().isEmpty() ? QString() : QDir(m_directory).filePath(m_name.trimmed());
}

QString ProjectExport::displayPath() const
{
    const QString path = projectPath();
    const QString home = QDir::homePath();
    return path.startsWith(home + QLatin1Char('/')) ? QLatin1Char('~') + path.mid(home.size()) : path;
}

bool ProjectExport::exists() const
{
    const QString path = projectPath();
    return !path.isEmpty() && QFileInfo::exists(QDir(path).filePath(QStringLiteral("CMakeLists.txt")));
}

QString ProjectExport::suggestedName() const
{
    if (!m_session || !m_session->isOpen())
        return QString();
    QString base = QFileInfo(m_session->displayName()).completeBaseName();
    if (base.isEmpty())
        base = m_session->displayName();
    QString name;
    bool upper = true;
    for (const QChar c : base) {
        if (!c.isLetterOrNumber()) {
            upper = true;
            continue;
        }
        name += upper ? c.toUpper() : c;
        upper = false;
    }
    return name.isEmpty() ? QStringLiteral("Models") : name;
}

QString ProjectExport::defaultDirectory()
{
    return QDir(QStandardPaths::writableLocation(QStandardPaths::DocumentsLocation))
        .filePath(QStringLiteral("Qivot Projects"));
}

void ProjectExport::regenerate()
{
    m_files.clear();
    if (m_session && m_session->isOpen() && !m_name.trimmed().isEmpty())
        m_files = generate(*m_session, m_name.trimmed());
    emit filesChanged();
}

void ProjectExport::setError(const QString &error)
{
    if (error == m_error)
        return;
    m_error = error;
    emit errorChanged();
}

bool ProjectExport::write()
{
    const QString root = projectPath();
    if (root.isEmpty() || m_files.isEmpty()) {
        setError(tr("Open a database and name the project first."));
        return false;
    }
    for (auto it = m_files.cbegin(); it != m_files.cend(); ++it) {
        const QString path = QDir(root).filePath(it.key());
        if (!QDir().mkpath(QFileInfo(path).absolutePath())) {
            setError(tr("Couldn't create %1.").arg(QFileInfo(path).absolutePath()));
            return false;
        }
        QFile file(path);
        if (!file.open(QIODevice::WriteOnly) || file.write(it.value().toUtf8()) < 0) {
            setError(tr("Couldn't write %1: %2").arg(path, file.errorString()));
            return false;
        }
    }
    setError(QString());
    emit pathChanged();
    emit written();
    return true;
}

bool ProjectExport::writeFile(const QString &file)
{
    const QString root = projectPath();
    if (root.isEmpty() || !m_files.contains(file)) {
        setError(tr("There's no generated %1.").arg(file));
        return false;
    }
    const QString path = QDir(root).filePath(file);
    QDir().mkpath(QFileInfo(path).absolutePath());
    QFile out(path);
    if (!out.open(QIODevice::WriteOnly) || out.write(m_files.value(file).toUtf8()) < 0) {
        setError(tr("Couldn't write %1: %2").arg(path, out.errorString()));
        return false;
    }
    setError(QString());
    return true;
}

QMap<QString, QString> ProjectExport::generate(const DatabaseSession &session, const QString &name)
{
    const CodeGen gen(session.tableInfos(), session.dialect());
    const QVector<CodeGen::Model> models = gen.models();
    const QVariantMap settings = session.connectionSettings();
    const QString source = settings.value(QStringLiteral("type")).toString() == QLatin1String("sqlite")
                         ? session.displayName()
                         : QStringLiteral("%1 on %2").arg(session.displayName(), session.location());

    QStringList classes;
    for (const CodeGen::Model &m : models)
        classes << m.className;

    const QString ident = identifier(name);
    QMap<QString, QString> files;

    QStringList modelLines;
    for (const QString &c : classes)
        modelLines << QStringLiteral("    ") + c;
    files.insert(QStringLiteral("CMakeLists.txt"),
                 fill(QString::fromUtf8(CMakeTemplate),
                      { { QStringLiteral("NAME"), name }, { QStringLiteral("SOURCE"), source },
                        { QStringLiteral("IDENT"), ident }, { QStringLiteral("TARGET"), ident.toLower() },
                        { QStringLiteral("MODELS"), modelLines.join(QLatin1Char('\n')) } }));

    files.insert(QStringLiteral("README.md"),
                 fill(QString::fromUtf8(ReadmeTemplate),
                      { { QStringLiteral("NAME"), name }, { QStringLiteral("SOURCE"), source },
                        { QStringLiteral("COUNT"), QString::number(models.size()) },
                        { QStringLiteral("ENV"), environmentTable(settings) } }));

    // Qivot itself: the single header Studio was built with, so the project
    // builds as it is, offline, against the same Qivot.
    for (const char *f : { "qivot.hpp", "qivot.cpp", "LICENSE.txt", "NOTICE.txt" })
        files.insert(QStringLiteral("third_party/qivot/") + QLatin1String(f), qivotFile(QLatin1String(f)));

    files.insert(QStringLiteral("src/models.h"), gen.header());
    files.insert(QStringLiteral("src/database.h"), databaseHeader(settings));

    // main.cpp: a row count per model, then one foreign key followed.
    int width = 0;
    for (const QString &c : classes)
        width = qMax(width, int(c.size()));
    QString counts;
    for (const QString &c : classes)
        counts += QStringLiteral("    qInfo().noquote() << QStringLiteral(\"  ") + c.leftJustified(width)
                + QStringLiteral(" %1\").arg(") + c + QStringLiteral("::objects().count());\n");
    QString follows;
    const QString example = followExample(models, &follows);
    files.insert(QStringLiteral("src/main.cpp"),
                 fill(QString::fromUtf8(MainTemplate),
                      { { QStringLiteral("NAME"), name }, { QStringLiteral("SOURCE"), source },
                        { QStringLiteral("FOLLOWS"), follows }, { QStringLiteral("COUNTS"), counts },
                        { QStringLiteral("EXAMPLE"), example } }));

    // tests: one slot per model, named like it so `tst_models Album` runs one.
    QString testSlots;
    for (const CodeGen::Model &m : models) {
        QStringList checks;
        for (const CodeGen::Field &f : m.fields)
            if (!f.target.isEmpty())
                checks << fill(QStringLiteral(
                    "            QVERIFY2(follows(row.@FIELD@),\n"
                    "                     qPrintable(QStringLiteral(\"@FIELD@ = %1: no @TARGET@ row has that key\")\n"
                    "                                    .arg(row.@FIELD@.get().toString())));\n"),
                    { { QStringLiteral("FIELD"), f.name }, { QStringLiteral("TARGET"), f.target } });
        testSlots += QStringLiteral("\n    void %1()\n    {\n").arg(m.className);
        if (checks.isEmpty())
            testSlots += QStringLiteral("        loadsEveryRow<::%1>([](::%1 &, qint64) {});\n").arg(m.className);
        else
            testSlots += QStringLiteral("        loadsEveryRow<::%1>([](::%1 &row, qint64 n) {\n"
                                    "            if (n >= FollowedKeys)\n                return;\n%2"
                                    "        });\n").arg(m.className, checks.join(QString()));
        testSlots += QStringLiteral("    }\n");
    }
    files.insert(QStringLiteral("tests/tst_models.cpp"),
                 fill(QString::fromUtf8(TestTemplate),
                      { { QStringLiteral("SLOTS"), testSlots },
                        { QStringLiteral("FIRST"), classes.value(0, QStringLiteral("Model")) } }));
    return files;
}
