#include "sampleschema.h"

#include <QDate>
#include <QDateTime>
#include <QSqlError>
#include <QSqlQuery>

namespace {

const QString kOptional = QStringLiteral("--optional\n");
constexpr int kRowsPerInsert = 200;     // under every server's limit (SQL Server: 1000)

QString onDelete(const QString &action, const QString &dialect)
{
    if (action.isEmpty() || (dialect == QLatin1String("sqlserver") && action == QLatin1String("RESTRICT")))
        return QString();
    return QStringLiteral(" ON DELETE ") + action;
}

} // namespace

// ---- Building ----

void SampleSchema::addTable(const QString &name, const QList<Column> &columns)
{
    Table t;
    t.name = name;
    t.columns = columns;
    m_tables << t;
}

SampleSchema::Table *SampleSchema::find(const QString &name)
{
    for (Table &t : m_tables)
        if (t.name == name)
            return &t;
    Q_ASSERT_X(false, "SampleSchema", qPrintable(QStringLiteral("no table ") + name));
    return nullptr;
}

const SampleSchema::Table *SampleSchema::find(const QString &name) const
{
    for (const Table &t : m_tables)
        if (t.name == name)
            return &t;
    return nullptr;
}

void SampleSchema::primaryKey(const QString &table, const QStringList &columns) { find(table)->primaryKey = columns; }
void SampleSchema::unique(const QString &table, const QStringList &columns) { find(table)->uniques << columns; }
void SampleSchema::check(const QString &table, const QString &sql) { find(table)->checks << sql; }

void SampleSchema::foreignKey(const QString &table, const QStringList &columns, const QString &refTable,
                              const QStringList &refColumns, const QString &onDelete)
{
    find(table)->foreignKeys << ForeignKey{ columns, refTable, refColumns, onDelete };
}

void SampleSchema::index(const QString &name, const QString &table, const QStringList &columns, bool unique)
{
    m_indexes << Index{ name, table, columns, unique };
}

void SampleSchema::view(const QString &name, const QString &sql, const QString &sqliteSql)
{
    m_views << View{ name, sql, sqliteSql };
}

void SampleSchema::insert(const QString &table, const QVariantList &row)
{
    Table *t = find(table);
    Q_ASSERT(row.size() == t->columns.size());
    t->rows << row;
}

int SampleSchema::rowCount(const QString &table) const
{
    const Table *t = find(table);
    return t ? t->rows.size() : 0;
}

void SampleSchema::sqliteExtra(const QString &create, const QString &table, const QStringList &columns)
{
    m_extras << Extra{ create, table, columns, {} };
}

void SampleSchema::insertExtra(const QVariantList &row)
{
    m_extras.last().rows << row;
}

// ---- Writing ----

QString SampleSchema::type(const Column &c, const QString &dialect)
{
    const bool lite = dialect == QLatin1String("sqlite"), pg = dialect == QLatin1String("postgres"),
               my = dialect == QLatin1String("mysql");
    switch (c.kind) {
    case Id:
        return lite ? QStringLiteral("INTEGER PRIMARY KEY")
             : pg   ? QStringLiteral("INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY")
             : my   ? QStringLiteral("INT AUTO_INCREMENT PRIMARY KEY")
                    : QStringLiteral("INT IDENTITY(1,1) PRIMARY KEY");
    case Int:      return lite || pg ? QStringLiteral("INTEGER") : QStringLiteral("INT");
    case Text:     return lite ? QStringLiteral("TEXT")
                        : QStringLiteral("%1(%2)").arg(my || pg ? QStringLiteral("VARCHAR") : QStringLiteral("NVARCHAR")).arg(c.size);
    case LongText: return lite || pg || my ? QStringLiteral("TEXT") : QStringLiteral("NVARCHAR(MAX)");
    case Real:     return lite ? QStringLiteral("REAL") : pg ? QStringLiteral("DOUBLE PRECISION")
                        : my ? QStringLiteral("DOUBLE") : QStringLiteral("FLOAT");
    case Decimal:  return QStringLiteral("%1(%2,%3)").arg(lite || pg ? QStringLiteral("NUMERIC") : QStringLiteral("DECIMAL"))
                                                     .arg(c.size).arg(c.scale);
    case Date:     return QStringLiteral("DATE");
    case DateTime: return lite || my ? QStringLiteral("DATETIME") : pg ? QStringLiteral("TIMESTAMP") : QStringLiteral("DATETIME2(0)");
    case Bool:     return lite || pg || my ? QStringLiteral("BOOLEAN") : QStringLiteral("BIT");
    }
    return QString();
}

QString SampleSchema::literal(const QVariant &v, Kind kind, const QString &dialect)
{
    if (!v.isValid() || v.isNull())
        return QStringLiteral("NULL");
    switch (kind) {
    case Bool:
        if (dialect == QLatin1String("postgres"))
            return v.toBool() ? QStringLiteral("TRUE") : QStringLiteral("FALSE");
        return v.toBool() ? QStringLiteral("1") : QStringLiteral("0");
    case Id:
    case Int:
        return QString::number(v.toLongLong());
    case Real:
    case Decimal:
        return QString::number(v.toDouble(), 'g', 15);
    case Date:
        if (v.canConvert<QDate>() && v.toDate().isValid())
            return QLatin1Char('\'') + v.toDate().toString(Qt::ISODate) + QLatin1Char('\'');
        break;
    case DateTime:
        if (v.canConvert<QDateTime>() && v.toDateTime().isValid())
            return QLatin1Char('\'')
                   + v.toDateTime().toString(dialect == QLatin1String("sqlite") ? QStringLiteral("yyyy-MM-ddTHH:mm:ss")
                                                                               : QStringLiteral("yyyy-MM-dd HH:mm:ss"))
                   + QLatin1Char('\'');
        break;
    case Text:
    case LongText:
        break;
    }
    QString s = v.toString();
    s.replace(QLatin1Char('\''), QStringLiteral("''"));
    return QLatin1Char('\'') + s + QLatin1Char('\'');
}

QStringList SampleSchema::inserts(const QString &table, const QList<Column> &columns,
                                  const QList<QVariantList> &rows, const QString &dialect)
{
    QStringList names;
    for (const Column &c : columns)
        names << c.name;
    const QString head = QStringLiteral("INSERT INTO %1 (%2) VALUES\n").arg(table, names.join(QStringLiteral(", ")));
    QStringList out;
    for (int start = 0; start < rows.size(); start += kRowsPerInsert) {
        QStringList values;
        for (int r = start; r < qMin(rows.size(), start + kRowsPerInsert); ++r) {
            QStringList cells;
            for (int c = 0; c < columns.size(); ++c)
                cells << literal(rows.at(r).value(c), columns.at(c).kind, dialect);
            values << QLatin1Char('(') + cells.join(QStringLiteral(", ")) + QLatin1Char(')');
        }
        out << head + values.join(QStringLiteral(",\n"));
    }
    return out;
}

QString SampleSchema::viewSql(const View &v, const QString &dialect)
{
    QString sql = dialect == QLatin1String("sqlite") && !v.sqliteSql.isEmpty() ? v.sqliteSql : v.sql;
    sql.replace(QStringLiteral("%TRUE%"), literal(true, Bool, dialect));
    sql.replace(QStringLiteral("%FALSE%"), literal(false, Bool, dialect));
    return sql;
}

QStringList SampleSchema::statements(const QString &dialect) const
{
    const bool lite = dialect == QLatin1String("sqlite");
    QStringList out;
    if (lite)
        out << QStringLiteral("PRAGMA foreign_keys = OFF");     // rows load in any order

    // Tables. SQLite gets its references here; the servers get them after the rows.
    for (const Table &t : m_tables) {
        QStringList lines;
        for (const Column &c : t.columns) {
            QString line = c.name + QLatin1Char(' ') + type(c, dialect);
            if (c.notNull) line += QStringLiteral(" NOT NULL");
            if (c.isUnique) line += QStringLiteral(" UNIQUE");
            if (c.def.isValid()) line += QStringLiteral(" DEFAULT ") + literal(c.def, c.kind, dialect);
            if (!c.checkSql.isEmpty()) line += QStringLiteral(" CHECK (%1)").arg(c.checkSql);
            if (lite && !c.refTable.isEmpty())
                line += QStringLiteral(" REFERENCES %1(%2)").arg(c.refTable, c.refColumn) + onDelete(c.refOnDelete, dialect);
            lines << line;
        }
        if (!t.primaryKey.isEmpty())
            lines << QStringLiteral("PRIMARY KEY (%1)").arg(t.primaryKey.join(QStringLiteral(", ")));
        for (const QStringList &u : t.uniques)
            lines << QStringLiteral("UNIQUE (%1)").arg(u.join(QStringLiteral(", ")));
        for (const QString &c : t.checks)
            lines << QStringLiteral("CHECK (%1)").arg(c);
        if (lite)
            for (const ForeignKey &fk : t.foreignKeys)
                lines << QStringLiteral("FOREIGN KEY (%1) REFERENCES %2(%3)")
                             .arg(fk.columns.join(QStringLiteral(", ")), fk.refTable, fk.refColumns.join(QStringLiteral(", ")))
                             + onDelete(fk.onDelete, dialect);
        out << QStringLiteral("CREATE TABLE %1 (\n  %2)").arg(t.name, lines.join(QStringLiteral(",\n  ")));
    }
    if (lite) {
        for (const Index &i : m_indexes)
            out << QStringLiteral("CREATE %1INDEX %2 ON %3(%4)")
                       .arg(i.unique ? QStringLiteral("UNIQUE ") : QString(), i.name, i.table, i.columns.join(QStringLiteral(", ")));
        for (const View &v : m_views)
            out << QStringLiteral("CREATE VIEW %1 AS\n%2").arg(v.name, viewSql(v, dialect));
        for (const Extra &e : m_extras)
            out << kOptional + e.create;
    }

    // Rows.
    if (lite)
        out << QStringLiteral("BEGIN");
    for (const Table &t : m_tables) {
        const bool identity = dialect == QLatin1String("sqlserver") && !t.columns.isEmpty() && t.columns.first().kind == Id;
        if (identity) out << QStringLiteral("SET IDENTITY_INSERT %1 ON").arg(t.name);
        out << inserts(t.name, t.columns, t.rows, dialect);
        if (identity) out << QStringLiteral("SET IDENTITY_INSERT %1 OFF").arg(t.name);
    }
    if (lite) {
        for (const Extra &e : m_extras) {
            QList<Column> columns;
            for (const QString &c : e.columns)
                columns << Column::text(c, 0);
            for (const QString &s : inserts(e.table, columns, e.rows, dialect))
                out << kOptional + s;
        }
        out << QStringLiteral("COMMIT");
        out << QStringLiteral("PRAGMA user_version = %1").arg(m_version);
        return out;
    }

    // Servers: references, indexes and views once the rows are in.
    for (const Table &t : m_tables) {
        for (const Column &c : t.columns)
            if (!c.refTable.isEmpty())
                out << QStringLiteral("ALTER TABLE %1 ADD CONSTRAINT fk_%1_%2 FOREIGN KEY (%2) REFERENCES %3 (%4)")
                           .arg(t.name, c.name, c.refTable, c.refColumn) + onDelete(c.refOnDelete, dialect);
        for (const ForeignKey &fk : t.foreignKeys)
            out << QStringLiteral("ALTER TABLE %1 ADD CONSTRAINT fk_%1_%2 FOREIGN KEY (%3) REFERENCES %4 (%5)")
                       .arg(t.name, fk.refTable, fk.columns.join(QStringLiteral(", ")), fk.refTable,
                            fk.refColumns.join(QStringLiteral(", "))) + onDelete(fk.onDelete, dialect);
    }
    for (const Index &i : m_indexes)
        out << QStringLiteral("CREATE %1INDEX %2 ON %3 (%4)")
                   .arg(i.unique ? QStringLiteral("UNIQUE ") : QString(), i.name, i.table, i.columns.join(QStringLiteral(", ")));
    for (const View &v : m_views)
        out << QStringLiteral("CREATE VIEW %1 AS\n%2").arg(v.name, viewSql(v, dialect));
    // PostgreSQL's identities don't move past explicit ids by themselves.
    if (dialect == QLatin1String("postgres"))
        for (const Table &t : m_tables)
            if (!t.columns.isEmpty() && t.columns.first().kind == Id)
                out << QStringLiteral("SELECT setval(pg_get_serial_sequence('%1', '%2'), COALESCE(MAX(%2), 1)) FROM %1")
                           .arg(t.name, t.columns.first().name);
    return out;
}

bool SampleSchema::execute(QSqlDatabase db, const QString &dialect, QString *error) const
{
    QSqlQuery q(db);
    bool skipOptional = false;
    for (QString sql : statements(dialect)) {
        const bool optional = sql.startsWith(kOptional);
        if (optional) {
            if (skipOptional)
                continue;
            sql = sql.mid(kOptional.size());
        }
        if (q.exec(sql))
            continue;
        if (optional) {                 // e.g. this SQLite has no FTS5: go without
            skipOptional = true;
            continue;
        }
        if (error)
            *error = q.lastError().text() + QStringLiteral(" — ") + sql.left(120);
        if (dialect == QLatin1String("sqlite"))
            q.exec(QStringLiteral("ROLLBACK"));
        return false;
    }
    return true;
}

QString SampleSchema::script(const QString &dialect, const QString &database) const
{
    QString out;
    const bool mssql = dialect == QLatin1String("sqlserver");
    const QString end = mssql ? QStringLiteral(";\nGO\n") : QStringLiteral(";\n");
    out += QStringLiteral("-- The \"%1\" sample database, made by Qivot Studio (tools/sample-servers).\n").arg(database);
    if (dialect == QLatin1String("postgres"))
        out += QStringLiteral("CREATE DATABASE %1;\n\\connect %1\n").arg(database);
    else if (dialect == QLatin1String("mysql"))
        out += QStringLiteral("CREATE DATABASE %1;\nUSE %1;\nSET NAMES utf8mb4;\n").arg(database);
    else
        out += QStringLiteral("SET NOCOUNT ON;\nGO\nCREATE DATABASE %1;\nGO\nUSE %1;\nGO\n").arg(database);
    for (const QString &s : statements(dialect))
        out += s + end;
    return out;
}
