#ifndef SAMPLESCHEMA_H
#define SAMPLESCHEMA_H

#include <QList>
#include <QSqlDatabase>
#include <QString>
#include <QStringList>
#include <QVariant>

/// A sample database described once — tables, keys, references, checks,
/// indexes, views and rows — and written out for SQLite, PostgreSQL, MySQL or
/// SQL Server, each in its own types and rules:
///
///  - auto-numbered keys: INTEGER PRIMARY KEY, GENERATED BY DEFAULT AS
///    IDENTITY, AUTO_INCREMENT or IDENTITY(1,1) (rows carry explicit ids, so
///    every database gets the same ones);
///  - SQLite gets its references inline; the servers get them added after
///    the rows (so circular references load, and loading is quick);
///  - SQL Server has no ON DELETE RESTRICT: it's NO ACTION there.
class SampleSchema
{
public:
    enum Kind { Id, Int, Text, LongText, Real, Decimal, Date, DateTime, Bool };

    struct Column {
        QString name;
        Kind kind = Int;
        int size = 0, scale = 0;          // Text: length; Decimal: precision, scale
        bool notNull = false;
        bool isUnique = false;
        QVariant def;                     // a value, written as each database's literal
        QString checkSql;
        QString refTable, refColumn, refOnDelete;

        static Column id(const QString &name = QStringLiteral("id")) { return make(name, Id); }
        static Column integer(const QString &name) { return make(name, Int); }
        static Column text(const QString &name, int size) { Column c = make(name, Text); c.size = size; return c; }
        static Column longText(const QString &name) { return make(name, LongText); }
        static Column real(const QString &name) { return make(name, Real); }
        static Column decimal(const QString &name, int precision, int scale)
        { Column c = make(name, Decimal); c.size = precision; c.scale = scale; return c; }
        static Column date(const QString &name) { return make(name, Date); }
        static Column dateTime(const QString &name) { return make(name, DateTime); }
        static Column boolean(const QString &name) { return make(name, Bool); }

        Column required() const { Column c = *this; c.notNull = true; return c; }
        Column unique() const { Column c = *this; c.isUnique = true; return c; }
        Column defaultTo(const QVariant &v) const { Column c = *this; c.def = v; return c; }
        Column check(const QString &sql) const { Column c = *this; c.checkSql = sql; return c; }
        Column references(const QString &table, const QString &column = QStringLiteral("id"),
                          const QString &onDelete = QString()) const
        { Column c = *this; c.refTable = table; c.refColumn = column; c.refOnDelete = onDelete; return c; }

    private:
        static Column make(const QString &name, Kind kind) { Column c; c.name = name; c.kind = kind; return c; }
    };

    struct ForeignKey { QStringList columns; QString refTable; QStringList refColumns; QString onDelete; };
    struct Table {
        QString name;
        QList<Column> columns;
        QStringList primaryKey;           // a composite key (an Id column is its own)
        QList<QStringList> uniques;
        QStringList checks;
        QList<ForeignKey> foreignKeys;    // composite references (single ones are on the column)
        QList<QVariantList> rows;         // every column, in order
    };
    struct Index { QString name, table; QStringList columns; bool unique = false; };
    struct View { QString name, sql, sqliteSql; };
    struct Extra { QString create; QString table; QStringList columns; QList<QVariantList> rows; };

    explicit SampleSchema(int version = 1) : m_version(version) {}

    void addTable(const QString &name, const QList<Column> &columns);
    void primaryKey(const QString &table, const QStringList &columns);
    void unique(const QString &table, const QStringList &columns);
    void check(const QString &table, const QString &sql);
    void foreignKey(const QString &table, const QStringList &columns, const QString &refTable,
                    const QStringList &refColumns, const QString &onDelete = QString());
    void index(const QString &name, const QString &table, const QStringList &columns, bool unique = false);
    /// `sqliteSql`, when given, replaces `sql` on SQLite. %TRUE% and %FALSE%
    /// become each database's own (SQL Server has no TRUE).
    void view(const QString &name, const QString &sql, const QString &sqliteSql = QString());
    void insert(const QString &table, const QVariantList &row);
    int rowCount(const QString &table) const;

    /// SQLite only, and optional: a table SQLite may not support (FTS5), with its rows.
    void sqliteExtra(const QString &create, const QString &table, const QStringList &columns);
    void insertExtra(const QVariantList &row);

    const QList<Table> &tables() const { return m_tables; }

    /// The statements that build the sample on `dialect` ("sqlite", "postgres",
    /// "mysql", "sqlserver"), in order. Optional ones (the SQLite extras) are
    /// prefixed with "--optional\n".
    QStringList statements(const QString &dialect) const;
    /// Run them on an open, empty database.
    bool execute(QSqlDatabase db, const QString &dialect, QString *error = nullptr) const;
    /// A self-contained script for the server's own client (psql, mysql,
    /// sqlcmd) that creates `database` and fills it.
    QString script(const QString &dialect, const QString &database) const;

private:
    Table *find(const QString &name);
    const Table *find(const QString &name) const;
    static QString type(const Column &c, const QString &dialect);
    static QString viewSql(const View &v, const QString &dialect);
    static QString literal(const QVariant &v, Kind kind, const QString &dialect);
    static QStringList inserts(const QString &table, const QList<Column> &columns,
                               const QList<QVariantList> &rows, const QString &dialect);

    int m_version;
    QList<Table> m_tables;
    QList<Index> m_indexes;
    QList<View> m_views;
    QList<Extra> m_extras;
};

#endif // SAMPLESCHEMA_H
