#include "schemadesign.h"

#include "codegen.h"
#include "diagramdata.h"

#include <QDir>
#include <QFile>
#include <QFileInfo>
#include <QHash>
#include <QLocale>
#include <QRegularExpression>
#include <QSet>
#include <QSqlDatabase>
#include <QSqlError>
#include <QSqlQuery>
#include <QCryptographicHash>
#include <QJsonArray>
#include <QJsonDocument>
#include <QJsonObject>
#include <QStandardPaths>
#include <QUrl>
#include <QUuid>
#include <algorithm>

// ============================================================================
// Migration
// ============================================================================

namespace {

const QSet<QString> &reserved()
{
    static const QSet<QString> words = [] {
        QSet<QString> s;
        for (const char *w : { "all", "and", "as", "asc", "by", "case", "check", "column", "constraint", "create",
                               "default", "delete", "desc", "distinct", "drop", "else", "end", "from", "group",
                               "having", "in", "index", "insert", "into", "is", "join", "key", "limit", "not",
                               "null", "offset", "on", "or", "order", "primary", "references", "select", "set",
                               "table", "then", "to", "union", "unique", "update", "user", "values", "when",
                               "where", "with" })
            s.insert(QString::fromLatin1(w));
        return s;
    }();
    return words;
}

QString quoteOne(const QString &id, const QString &dialect)
{
    static const QRegularExpression lower(QStringLiteral("^[a-z_][a-z0-9_]*$"));
    static const QRegularExpression any(QStringLiteral("^[A-Za-z_][A-Za-z0-9_]*$"));
    const bool bare = (dialect == QLatin1String("postgres") ? lower : any).match(id).hasMatch()
                   && !reserved().contains(id.toLower());
    if (bare)
        return id;
    if (dialect == QLatin1String("mysql"))
        return QLatin1Char('`') + QString(id).replace(QLatin1Char('`'), QLatin1String("``")) + QLatin1Char('`');
    if (dialect == QLatin1String("sqlserver"))
        return QLatin1Char('[') + QString(id).replace(QLatin1Char(']'), QLatin1String("]]")) + QLatin1Char(']');
    return QLatin1Char('"') + QString(id).replace(QLatin1Char('"'), QLatin1String("\"\"")) + QLatin1Char('"');
}

// A table name, schema-qualified ones ("sales.orders") quoted part by part.
QString qt(const QString &name, const QString &dialect)
{
    const int dot = name.indexOf(QLatin1Char('.'));
    return dot > 0 ? quoteOne(name.left(dot), dialect) + QLatin1Char('.') + quoteOne(name.mid(dot + 1), dialect)
                   : quoteOne(name, dialect);
}

QString qlist(const QStringList &names, const QString &dialect)
{
    QStringList out;
    for (const QString &n : names)
        out << quoteOne(n, dialect);
    return out.join(QStringLiteral(", "));
}

QString bareName(const QString &table)
{
    const int dot = table.indexOf(QLatin1Char('.'));
    return dot > 0 ? table.mid(dot + 1) : table;
}

bool isUnique(const QiTableInfo &t, const QString &column)
{
    for (const QiIndexInfo &i : t.indexes)
        if (i.unique && i.columns == QStringList{ column })
            return true;
    return false;
}

int columnIndex(const QiTableInfo &t, const QString &name)
{
    for (int i = 0; i < t.columns.size(); ++i)
        if (t.columns.at(i).name == name)
            return i;
    return -1;
}

QString defaultOf(const QiColumnInfo &c)
{
    return c.defaultValue.isNull() ? QString() : c.defaultValue.toString().trimmed();
}

QString columnDefinition(const QiTableInfo &t, const QiColumnInfo &c, const QString &dialect, bool withUnique)
{
    QString def = quoteOne(c.name, dialect) + QLatin1Char(' ');
    const bool soleKey = t.primaryKey == QStringList{ c.name };
    const QString type = c.type.trimmed().isEmpty() ? QStringLiteral("TEXT") : c.type.trimmed();
    if (soleKey && c.autoIncrement) {
        if (dialect == QLatin1String("sqlite"))
            return def + QStringLiteral("INTEGER PRIMARY KEY AUTOINCREMENT");
        if (dialect == QLatin1String("postgres"))
            return def + (type.contains(QLatin1String("serial"), Qt::CaseInsensitive)
                              ? type + QStringLiteral(" PRIMARY KEY")
                              : type + QStringLiteral(" GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"));
        if (dialect == QLatin1String("mysql"))
            return def + type + QStringLiteral(" NOT NULL AUTO_INCREMENT PRIMARY KEY");
        if (dialect == QLatin1String("sqlserver"))
            return def + type + QStringLiteral(" IDENTITY(1,1) PRIMARY KEY");
    }
    def += type;
    if (soleKey)
        def += QStringLiteral(" PRIMARY KEY");
    if (!c.nullable && !soleKey)
        def += QStringLiteral(" NOT NULL");
    const QString d = defaultOf(c);
    if (!d.isEmpty())
        def += QStringLiteral(" DEFAULT ") + d;
    if (withUnique && !soleKey && isUnique(t, c.name))
        def += QStringLiteral(" UNIQUE");
    return def;
}

QString fkClause(const QiForeignKeyInfo &fk, const QString &dialect)
{
    QString s = QStringLiteral("FOREIGN KEY (%1) REFERENCES %2 (%3)")
                    .arg(qlist(fk.columns, dialect), qt(fk.refTable, dialect), qlist(fk.refColumns, dialect));
    const QString del = fk.onDelete.toUpper();
    if (!del.isEmpty() && del != QLatin1String("NO ACTION") && !(dialect == QLatin1String("sqlserver") && del == QLatin1String("RESTRICT")))
        s += QStringLiteral(" ON DELETE ") + del;
    return s;
}

QString fkSignature(const QiForeignKeyInfo &fk)
{
    const QString del = fk.onDelete.toUpper() == QLatin1String("RESTRICT") ? QStringLiteral("NO ACTION") : fk.onDelete.toUpper();
    return fk.columns.join(QLatin1Char(',')) + QLatin1String("->") + fk.refTable + QLatin1Char('(')
         + fk.refColumns.join(QLatin1Char(',')) + QLatin1String(") ") + (del.isEmpty() ? QStringLiteral("NO ACTION") : del);
}

// Everything that differs between the database and the design.
struct ColumnChange {
    const QiColumnInfo *before = nullptr;
    const QiColumnInfo *after = nullptr;
    bool renamed = false, type = false, nullable = false, def = false;
    bool any() const { return renamed || type || nullable || def; }
};

struct TableDiff {
    const QiTableInfo *before = nullptr;
    const DesignTable *after = nullptr;
    bool renamed = false;
    QStringList droppedColumns;                  // original names
    QVector<const QiColumnInfo *> addedColumns;
    QVector<ColumnChange> changedColumns;
    bool keyChanged = false;
    QVector<QiForeignKeyInfo> droppedKeys;       // as in the database
    QVector<QiForeignKeyInfo> addedKeys;         // as in the design
    QStringList addedUnique;                     // design column names
    QVector<QiIndexInfo> droppedUnique;          // as in the database
    QStringList droppedUniqueColumns;            // their columns' names in the design (or original if dropped)

    bool changed() const
    {
        return renamed || !droppedColumns.isEmpty() || !addedColumns.isEmpty() || !changedColumns.isEmpty()
            || keyChanged || !droppedKeys.isEmpty() || !addedKeys.isEmpty() || !addedUnique.isEmpty()
            || !droppedUnique.isEmpty();
    }
    // SQLite can rename, add a plain column and add a unique index; anything else is a rebuild.
    bool sqliteNeedsRebuild() const
    {
        if (!droppedColumns.isEmpty() || keyChanged || !droppedKeys.isEmpty() || !addedKeys.isEmpty())
            return true;
        for (const ColumnChange &c : changedColumns)
            if (c.type || c.nullable || c.def)
                return true;
        for (const QiColumnInfo *c : addedColumns)
            if ((!c->nullable && defaultOf(*c).isEmpty()) || after->info.primaryKey.contains(c->name))
                return true;
        for (const QiIndexInfo &i : droppedUnique)
            if (i.implicit)
                return true;
        return false;
    }
};

struct Diff {
    QVector<const QiTableInfo *> droppedTables;
    QVector<const DesignTable *> createdTables;
    QVector<TableDiff> tables;                  // the ones that exist on both sides
};

Diff diff(const QVector<QiTableInfo> &original, const QVector<DesignTable> &design)
{
    Diff d;
    QHash<QString, const QiTableInfo *> byName;
    for (const QiTableInfo &t : original)
        byName.insert(t.name, &t);

    // Table and column renames, to read the database's keys in the design's names.
    QHash<QString, QString> tableName;                       // original -> design
    QHash<QString, QHash<QString, QString>> columnName;      // original table -> original column -> design column
    QSet<QString> kept;
    for (const DesignTable &t : design) {
        if (t.origin.isEmpty() || !byName.contains(t.origin)) {
            d.createdTables << &t;
            continue;
        }
        kept.insert(t.origin);
        tableName.insert(t.origin, t.info.name);
        for (int i = 0; i < t.info.columns.size(); ++i)
            if (!t.columnOrigins.value(i).isEmpty())
                columnName[t.origin].insert(t.columnOrigins.at(i), t.info.columns.at(i).name);
    }
    for (const QiTableInfo &t : original)
        if (!kept.contains(t.name) && t.kind == QiTableInfo::Table)
            d.droppedTables << &t;

    auto mapKey = [&](const QiTableInfo &owner, const QiForeignKeyInfo &fk, bool *ok) {
        QiForeignKeyInfo m = fk;
        *ok = tableName.contains(fk.refTable);
        m.refTable = tableName.value(fk.refTable);
        m.columns.clear();
        m.refColumns.clear();
        for (const QString &c : fk.columns) {
            *ok = *ok && columnName[owner.name].contains(c);
            m.columns << columnName[owner.name].value(c);
        }
        for (const QString &c : fk.refColumns) {
            *ok = *ok && columnName[fk.refTable].contains(c);
            m.refColumns << columnName[fk.refTable].value(c);
        }
        return m;
    };

    for (const DesignTable &t : design) {
        if (t.origin.isEmpty() || !byName.contains(t.origin))
            continue;
        TableDiff td;
        td.before = byName.value(t.origin);
        td.after = &t;
        td.renamed = t.info.name != t.origin;
        const QHash<QString, QString> &cols = columnName[t.origin];

        QSet<QString> keptColumns;
        for (int i = 0; i < t.info.columns.size(); ++i) {
            const QiColumnInfo &c = t.info.columns.at(i);
            const QString origin = t.columnOrigins.value(i);
            const QiColumnInfo *before = origin.isEmpty() ? nullptr : td.before->column(origin);
            if (!before) {
                td.addedColumns << &c;
                continue;
            }
            keptColumns.insert(origin);
            ColumnChange cc;
            cc.before = before;
            cc.after = &c;
            cc.renamed = c.name != before->name;
            cc.type = c.type.trimmed().compare(before->type.trimmed(), Qt::CaseInsensitive) != 0;
            cc.nullable = c.nullable != before->nullable && !t.info.primaryKey.contains(c.name);
            cc.def = defaultOf(c) != defaultOf(*before) && !c.autoIncrement;
            if (cc.any())
                td.changedColumns << cc;
        }
        for (const QiColumnInfo &c : td.before->columns)
            if (!keptColumns.contains(c.name))
                td.droppedColumns << c.name;

        QStringList keyBefore;
        for (const QString &c : td.before->primaryKey)
            keyBefore << cols.value(c, QStringLiteral("\x01"));
        td.keyChanged = keyBefore != t.info.primaryKey;

        QSet<QString> afterKeys;
        for (const QiForeignKeyInfo &fk : t.info.foreignKeys)
            afterKeys.insert(fkSignature(fk));
        QSet<QString> beforeKeys;
        for (const QiForeignKeyInfo &fk : td.before->foreignKeys) {
            bool ok = false;
            const QiForeignKeyInfo mapped = mapKey(*td.before, fk, &ok);
            if (ok)
                beforeKeys.insert(fkSignature(mapped));
            if (!ok || !afterKeys.contains(fkSignature(mapped)))
                td.droppedKeys << fk;
        }
        for (const QiForeignKeyInfo &fk : t.info.foreignKeys)
            if (!beforeKeys.contains(fkSignature(fk)))
                td.addedKeys << fk;

        // Unique columns (single-column unique indexes and constraints).
        for (const QiIndexInfo &i : td.before->indexes) {
            if (!i.unique || i.columns.size() != 1 || td.before->primaryKey == i.columns)
                continue;
            const QString now = cols.value(i.columns.first());
            if (now.isEmpty() || !isUnique(t.info, now)) {
                td.droppedUnique << i;
                td.droppedUniqueColumns << (now.isEmpty() ? i.columns.first() : now);
            }
        }
        for (int k = 0; k < t.info.columns.size(); ++k) {
            const QiColumnInfo &c = t.info.columns.at(k);
            const QString origin = t.columnOrigins.value(k);
            if (origin.isEmpty() || !isUnique(t.info, c.name) || t.info.primaryKey == QStringList{ c.name })
                continue;                       // new columns carry their own UNIQUE
            bool before = false;
            for (const QiIndexInfo &i : td.before->indexes)
                before = before || (i.unique && i.columns == QStringList{ origin });
            if (!before)
                td.addedUnique << c.name;
        }
        if (td.changed())
            d.tables << td;
    }
    return d;
}

// New tables in an order where each one's references already exist.
QVector<const DesignTable *> creationOrder(const QVector<const DesignTable *> &created)
{
    QVector<const DesignTable *> out, pending = created;
    QSet<QString> pendingNames;
    for (const DesignTable *t : created)
        pendingNames.insert(t->info.name);
    while (!pending.isEmpty()) {
        int pick = 0;
        for (int i = 0; i < pending.size(); ++i) {
            bool ready = true;
            for (const QiForeignKeyInfo &fk : pending[i]->info.foreignKeys)
                ready = ready && (fk.refTable == pending[i]->info.name || !pendingNames.contains(fk.refTable));
            if (ready) { pick = i; break; }
        }
        pendingNames.remove(pending[pick]->info.name);
        out << pending.takeAt(pick);
    }
    return out;
}

QString constraintName(const QString &prefix, const QString &table, const QStringList &columns)
{
    return prefix + QLatin1Char('_') + bareName(table) + QLatin1Char('_') + columns.join(QLatin1Char('_'));
}

} // namespace

QString Migration::quoted(const QString &identifier, const QString &dialect)
{
    return qt(identifier, dialect);
}

// CREATE INDEX for the indexes CREATE TABLE doesn't write: all but the key
// and single-column unique ones (which are inline).
static QString createIndexes(const QiTableInfo &t, const QString &dialect)
{
    QString sql;
    for (const QiIndexInfo &i : t.indexes) {
        if (i.columns.isEmpty() || i.columns.contains(QString()) || i.columns == t.primaryKey
            || (i.unique && i.columns.size() == 1))
            continue;
        const QString name = i.implicit || i.name.isEmpty() ? constraintName(i.unique ? QStringLiteral("ux") : QStringLiteral("ix"), t.name, i.columns)
                                                            : bareName(i.name);
        sql += QStringLiteral("CREATE %1INDEX %2 ON %3 (%4);\n")
                   .arg(i.unique ? QStringLiteral("UNIQUE ") : QString(), quoteOne(name, dialect), qt(t.name, dialect),
                        qlist(i.columns, dialect));
    }
    return sql;
}

QString Migration::createTable(const QiTableInfo &t, const QString &dialect)
{
    QStringList parts;
    for (const QiColumnInfo &c : t.columns)
        parts << QStringLiteral("    ") + columnDefinition(t, c, dialect, true);
    if (t.primaryKey.size() > 1)
        parts << QStringLiteral("    PRIMARY KEY (%1)").arg(qlist(t.primaryKey, dialect));
    for (const QiForeignKeyInfo &fk : t.foreignKeys)
        parts << QStringLiteral("    ") + fkClause(fk, dialect);
    return QStringLiteral("CREATE TABLE %1 (\n%2\n);\n").arg(qt(t.name, dialect), parts.join(QStringLiteral(",\n")))
         + createIndexes(t, dialect);
}

QString Migration::sql(const QVector<QiTableInfo> &original, const QVector<DesignTable> &design, const QString &dialect)
{
    const Diff d = diff(original, design);
    if (d.droppedTables.isEmpty() && d.createdTables.isEmpty() && d.tables.isEmpty())
        return QString();

    const bool sqlite = dialect == QLatin1String("sqlite");
    const bool mysql = dialect == QLatin1String("mysql");
    const bool mssql = dialect == QLatin1String("sqlserver");
    const bool pg = dialect == QLatin1String("postgres");
    QStringList out;
    auto section = [&](const QString &title) { out << QStringLiteral("\n-- %1").arg(title); };

    bool rebuilds = false;
    for (const TableDiff &t : d.tables)
        rebuilds = rebuilds || (sqlite && t.sqliteNeedsRebuild());
    if (rebuilds)
        out << QStringLiteral("PRAGMA foreign_keys = OFF;   -- while tables are rebuilt");
    if (sqlite || pg)
        out << QStringLiteral("BEGIN;");
    else if (mssql)
        out << QStringLiteral("BEGIN TRANSACTION;");
    else
        out << QStringLiteral("-- MySQL commits each schema change as it goes; there is no undoing half of this.");

    // 1. Foreign keys that go away (not SQLite: there they go with the rebuild).
    if (!sqlite) {
        bool first = true;
        for (const TableDiff &t : d.tables)
            for (const QiForeignKeyInfo &fk : t.droppedKeys) {
                if (first) { section(QStringLiteral("Foreign keys that change or go away")); first = false; }
                if (fk.name.isEmpty())
                    out << QStringLiteral("-- %1 (%2): this foreign key has no name; drop it by hand.")
                               .arg(t.before->name, fk.columns.join(QStringLiteral(", ")));
                else
                    out << QStringLiteral("ALTER TABLE %1 DROP %2 %3;")
                               .arg(qt(t.before->name, dialect), mysql ? QStringLiteral("FOREIGN KEY") : QStringLiteral("CONSTRAINT"),
                                    quoteOne(fk.name, dialect));
            }
    }

    // 2. Tables that go away.
    if (!d.droppedTables.isEmpty()) {
        section(QStringLiteral("Tables that go away (and their rows)"));
        for (const QiTableInfo *t : d.droppedTables)
            out << QStringLiteral("DROP TABLE %1;").arg(qt(t->name, dialect));
    }

    // 3. Renames, so everything below can use the new names. (SQLite too before
    //    a rebuild: its RENAME also updates the other tables' references.)
    QStringList renames;
    for (const TableDiff &t : d.tables) {
        const QString table = qt(t.after->info.name, dialect);
        if (t.renamed) {
            if (mssql)
                renames << QStringLiteral("EXEC sp_rename '%1', '%2';").arg(t.before->name, bareName(t.after->info.name));
            else if (mysql)
                renames << QStringLiteral("RENAME TABLE %1 TO %2;").arg(qt(t.before->name, dialect), table);
            else
                renames << QStringLiteral("ALTER TABLE %1 RENAME TO %2;").arg(qt(t.before->name, dialect), quoteOne(bareName(t.after->info.name), dialect));
        }
        for (const ColumnChange &c : t.changedColumns)
            if (c.renamed) {
                if (mssql)
                    renames << QStringLiteral("EXEC sp_rename '%1.%2', '%3', 'COLUMN';").arg(t.after->info.name, c.before->name, c.after->name);
                else
                    renames << QStringLiteral("ALTER TABLE %1 RENAME COLUMN %2 TO %3;")
                                   .arg(table, quoteOne(c.before->name, dialect), quoteOne(c.after->name, dialect));
            }
    }
    if (!renames.isEmpty()) {
        section(QStringLiteral("Renames"));
        out << renames;
    }

    // 4. New tables.
    const QVector<const DesignTable *> created = creationOrder(d.createdTables);
    if (!created.isEmpty()) {
        section(QStringLiteral("New tables"));
        for (const DesignTable *t : created)
            out << createTable(t->info, dialect).trimmed();
    }

    // 5. Changes to existing tables.
    for (const TableDiff &t : d.tables) {
        const QString table = qt(t.after->info.name, dialect);
        QStringList lines;
        if (sqlite && t.sqliteNeedsRebuild()) {
            // Rebuild: the new shape under a temporary name, the rows copied across by origin.
            const QString temp = QStringLiteral("_new_") + bareName(t.after->info.name);
            QiTableInfo shaped = t.after->info;
            shaped.name = temp;
            QStringList kept;                   // already renamed above, so the same name on both sides
            for (int i = 0; i < t.after->info.columns.size(); ++i) {
                const QString origin = t.after->columnOrigins.value(i);
                if (!origin.isEmpty() && t.before->column(origin))
                    kept << quoteOne(t.after->info.columns.at(i).name, dialect);
            }
            lines << QStringLiteral("-- SQLite can't alter these columns in place: rebuild %1, keeping its rows.")
                         .arg(t.after->info.name);
            QiTableInfo bare = shaped;
            bare.indexes.erase(std::remove_if(bare.indexes.begin(), bare.indexes.end(), [&](const QiIndexInfo &i) {
                                   return !(i.unique && i.columns.size() == 1); }),
                               bare.indexes.end());
            lines << createTable(bare, dialect).trimmed();
            if (!kept.isEmpty())
                lines << QStringLiteral("INSERT INTO %1 (%2)\n    SELECT %2 FROM %3;")
                             .arg(quoteOne(temp, dialect), kept.join(QStringLiteral(", ")), table);
            lines << QStringLiteral("DROP TABLE %1;").arg(table);
            lines << QStringLiteral("ALTER TABLE %1 RENAME TO %2;").arg(quoteOne(temp, dialect), quoteOne(bareName(t.after->info.name), dialect));
            // The other indexes went with the old table; recreate them on the new one.
            const QString indexes = createIndexes(t.after->info, dialect).trimmed();
            if (!indexes.isEmpty())
                lines << indexes;
        } else {
            for (const QString &c : t.droppedColumns)
                lines << QStringLiteral("ALTER TABLE %1 DROP COLUMN %2;").arg(table, quoteOne(c, dialect));
            for (const QiColumnInfo *c : t.addedColumns) {
                lines << QStringLiteral("ALTER TABLE %1 ADD %2%3;")
                             .arg(table, mssql ? QString() : QStringLiteral("COLUMN "),
                                  columnDefinition(t.after->info, *c, dialect, !sqlite));
                if (sqlite && isUnique(t.after->info, c->name))          // SQLite can't ADD COLUMN ... UNIQUE
                    lines << QStringLiteral("CREATE UNIQUE INDEX %1 ON %2 (%3);")
                                 .arg(quoteOne(constraintName(QStringLiteral("ux"), t.after->info.name, { c->name }), dialect),
                                      table, quoteOne(c->name, dialect));
            }
            for (const ColumnChange &c : t.changedColumns) {
                if (!(c.type || c.nullable || c.def))
                    continue;
                const QString col = quoteOne(c.after->name, dialect);
                if (pg) {
                    if (c.type)
                        lines << QStringLiteral("ALTER TABLE %1 ALTER COLUMN %2 TYPE %3 USING %2::%3;").arg(table, col, c.after->type);
                    if (c.nullable)
                        lines << QStringLiteral("ALTER TABLE %1 ALTER COLUMN %2 %3 NOT NULL;")
                                     .arg(table, col, c.after->nullable ? QStringLiteral("DROP") : QStringLiteral("SET"));
                    if (c.def)
                        lines << (defaultOf(*c.after).isEmpty()
                                      ? QStringLiteral("ALTER TABLE %1 ALTER COLUMN %2 DROP DEFAULT;").arg(table, col)
                                      : QStringLiteral("ALTER TABLE %1 ALTER COLUMN %2 SET DEFAULT %3;").arg(table, col, defaultOf(*c.after)));
                } else if (mysql) {
                    lines << QStringLiteral("ALTER TABLE %1 MODIFY COLUMN %2;").arg(table, columnDefinition(t.after->info, *c.after, dialect, false));
                } else if (mssql) {
                    if (c.type || c.nullable)
                        lines << QStringLiteral("ALTER TABLE %1 ALTER COLUMN %2 %3 %4;")
                                     .arg(table, col, c.after->type, c.after->nullable ? QStringLiteral("NULL") : QStringLiteral("NOT NULL"));
                    if (c.def)
                        lines << QStringLiteral("-- %1.%2: SQL Server keeps defaults as named constraints; drop the old one, then:\n"
                                                "ALTER TABLE %3 ADD DEFAULT %4 FOR %5;")
                                     .arg(t.after->info.name, c.after->name, table,
                                          defaultOf(*c.after).isEmpty() ? QStringLiteral("NULL") : defaultOf(*c.after), col);
                }
            }
            if (t.keyChanged) {
                if (pg)
                    lines << QStringLiteral("ALTER TABLE %1 DROP CONSTRAINT %2;").arg(table, quoteOne(bareName(t.before->name) + QStringLiteral("_pkey"), dialect));
                else if (mysql)
                    lines << QStringLiteral("ALTER TABLE %1 DROP PRIMARY KEY;").arg(table);
                else if (mssql)
                    lines << QStringLiteral("-- Drop %1's primary key constraint first (its name is in sys.key_constraints).").arg(t.after->info.name);
                if (!t.after->info.primaryKey.isEmpty())
                    lines << QStringLiteral("ALTER TABLE %1 ADD PRIMARY KEY (%2);").arg(table, qlist(t.after->info.primaryKey, dialect));
            }
            for (const QiForeignKeyInfo &fk : t.addedKeys)
                lines << QStringLiteral("ALTER TABLE %1 ADD CONSTRAINT %2 %3;")
                             .arg(table, quoteOne(constraintName(QStringLiteral("fk"), t.after->info.name, fk.columns), dialect),
                                  fkClause(fk, dialect));
            for (int i = 0; i < t.droppedUnique.size(); ++i) {
                const QiIndexInfo &index = t.droppedUnique.at(i);
                if (sqlite || !index.implicit)
                    lines << (mysql || mssql ? QStringLiteral("DROP INDEX %1 ON %2;").arg(quoteOne(index.name, dialect), table)
                                             : QStringLiteral("DROP INDEX %1;").arg(quoteOne(index.name, dialect)));
                else if (mysql)
                    lines << QStringLiteral("ALTER TABLE %1 DROP INDEX %2;").arg(table, quoteOne(index.name, dialect));
                else
                    lines << QStringLiteral("ALTER TABLE %1 DROP CONSTRAINT %2;").arg(table, quoteOne(index.name, dialect));
            }
            for (const QString &c : t.addedUnique)
                lines << QStringLiteral("CREATE UNIQUE INDEX %1 ON %2 (%3);")
                             .arg(quoteOne(constraintName(QStringLiteral("ux"), t.after->info.name, { c }), dialect), table, quoteOne(c, dialect));
        }
        if (!lines.isEmpty()) {
            section(t.after->info.name);
            out << lines;
        }
    }

    if (sqlite || pg || mssql)
        out << QStringLiteral("\nCOMMIT;");
    if (rebuilds)
        out << QStringLiteral("PRAGMA foreign_keys = ON;");
    return out.join(QLatin1Char('\n')).trimmed() + QLatin1Char('\n');
}

QStringList Migration::changedTables(const QVector<QiTableInfo> &original, const QVector<DesignTable> &design)
{
    QStringList out;
    for (const TableDiff &t : diff(original, design).tables)
        out << t.after->info.name;
    return out;
}

QStringList Migration::changes(const QVector<QiTableInfo> &original, const QVector<DesignTable> &design)
{
    const Diff d = diff(original, design);
    QStringList out;
    for (const DesignTable *t : d.createdTables)
        out << QStringLiteral("Create table %1").arg(t->info.name);
    for (const QiTableInfo *t : d.droppedTables)
        out << QStringLiteral("Drop table %1").arg(t->name);
    for (const TableDiff &t : d.tables) {
        const QString name = t.after->info.name;
        if (t.renamed)
            out << QStringLiteral("Rename table %1 → %2").arg(t.before->name, name);
        for (const QiColumnInfo *c : t.addedColumns)
            out << QStringLiteral("Add column %1.%2").arg(name, c->name);
        for (const QString &c : t.droppedColumns)
            out << QStringLiteral("Drop column %1.%2").arg(name, c);
        for (const ColumnChange &c : t.changedColumns) {
            if (c.renamed)
                out << QStringLiteral("Rename column %1.%2 → %3").arg(name, c.before->name, c.after->name);
            QStringList what;
            if (c.type)
                what << QStringLiteral("type %1 → %2").arg(c.before->type, c.after->type);
            if (c.nullable)
                what << (c.after->nullable ? QStringLiteral("allow NULL") : QStringLiteral("NOT NULL"));
            if (c.def)
                what << (defaultOf(*c.after).isEmpty() ? QStringLiteral("no default")
                                                       : QStringLiteral("default %1").arg(defaultOf(*c.after)));
            if (!what.isEmpty())
                out << QStringLiteral("Change %1.%2: %3").arg(name, c.after->name, what.join(QStringLiteral(", ")));
        }
        if (t.keyChanged)
            out << QStringLiteral("Primary key of %1 → (%2)").arg(name, t.after->info.primaryKey.join(QStringLiteral(", ")));
        for (const QiForeignKeyInfo &fk : t.droppedKeys)
            out << QStringLiteral("Remove reference %1.%2 → %3").arg(name, fk.columns.join(QStringLiteral(", ")), fk.refTable);
        for (const QiForeignKeyInfo &fk : t.addedKeys)
            out << QStringLiteral("Add reference %1.%2 → %3").arg(name, fk.columns.join(QStringLiteral(", ")), fk.refTable);
        for (const QString &c : t.addedUnique)
            out << QStringLiteral("Make %1.%2 unique").arg(name, c);
        for (const QString &c : t.droppedUniqueColumns)
            out << QStringLiteral("%1.%2 no longer unique").arg(name, c);
    }
    return out;
}

// ============================================================================
// SchemaDesign
// ============================================================================

SchemaDesign::SchemaDesign(QObject *parent)
    : QObject(parent)
{
    connect(this, &SchemaDesign::designChanged, this, &SchemaDesign::validate);
    connect(this, &SchemaDesign::designChanged, this, &SchemaDesign::autosave);
}

// ---- JSON ----

namespace {

QJsonObject tableToJson(const QiTableInfo &t)
{
    QJsonArray columns, foreignKeys, indexes;
    for (const QiColumnInfo &c : t.columns)
        columns << QJsonObject{ { QStringLiteral("name"), c.name }, { QStringLiteral("type"), c.type },
                                { QStringLiteral("nullable"), c.nullable }, { QStringLiteral("primaryKeyOrder"), c.primaryKeyOrder },
                                { QStringLiteral("autoIncrement"), c.autoIncrement },
                                { QStringLiteral("default"), c.defaultValue.isNull() ? QJsonValue() : QJsonValue(c.defaultValue.toString()) } };
    for (const QiForeignKeyInfo &fk : t.foreignKeys)
        foreignKeys << QJsonObject{ { QStringLiteral("name"), fk.name },
                                    { QStringLiteral("columns"), QJsonArray::fromStringList(fk.columns) },
                                    { QStringLiteral("refTable"), fk.refTable },
                                    { QStringLiteral("refColumns"), QJsonArray::fromStringList(fk.refColumns) },
                                    { QStringLiteral("onDelete"), fk.onDelete }, { QStringLiteral("onUpdate"), fk.onUpdate } };
    for (const QiIndexInfo &i : t.indexes)
        indexes << QJsonObject{ { QStringLiteral("name"), i.name }, { QStringLiteral("columns"), QJsonArray::fromStringList(i.columns) },
                                { QStringLiteral("unique"), i.unique }, { QStringLiteral("implicit"), i.implicit } };
    return { { QStringLiteral("name"), t.name }, { QStringLiteral("schema"), t.schema },
             { QStringLiteral("primaryKey"), QJsonArray::fromStringList(t.primaryKey) },
             { QStringLiteral("columns"), columns }, { QStringLiteral("foreignKeys"), foreignKeys },
             { QStringLiteral("indexes"), indexes } };
}

QStringList strings(const QJsonValue &v)
{
    QStringList out;
    for (const QJsonValue &s : v.toArray())
        out << s.toString();
    return out;
}

QiTableInfo tableFromJson(const QJsonObject &o)
{
    QiTableInfo t;
    t.name = o.value(QStringLiteral("name")).toString();
    t.schema = o.value(QStringLiteral("schema")).toString();
    t.kind = QiTableInfo::Table;
    t.primaryKey = strings(o.value(QStringLiteral("primaryKey")));
    for (const QJsonValue &v : o.value(QStringLiteral("columns")).toArray()) {
        const QJsonObject c = v.toObject();
        QiColumnInfo col;
        col.name = c.value(QStringLiteral("name")).toString();
        col.type = c.value(QStringLiteral("type")).toString();
        col.nullable = c.value(QStringLiteral("nullable")).toBool(true);
        col.primaryKeyOrder = c.value(QStringLiteral("primaryKeyOrder")).toInt();
        col.primaryKey = t.primaryKey.contains(col.name);
        col.autoIncrement = c.value(QStringLiteral("autoIncrement")).toBool();
        const QJsonValue d = c.value(QStringLiteral("default"));
        col.defaultValue = d.isString() ? QVariant(d.toString()) : QVariant();
        t.columns << col;
    }
    for (const QJsonValue &v : o.value(QStringLiteral("foreignKeys")).toArray()) {
        const QJsonObject f = v.toObject();
        QiForeignKeyInfo fk;
        fk.name = f.value(QStringLiteral("name")).toString();
        fk.columns = strings(f.value(QStringLiteral("columns")));
        fk.refTable = f.value(QStringLiteral("refTable")).toString();
        fk.refColumns = strings(f.value(QStringLiteral("refColumns")));
        fk.onDelete = f.value(QStringLiteral("onDelete")).toString();
        fk.onUpdate = f.value(QStringLiteral("onUpdate")).toString();
        t.foreignKeys << fk;
    }
    for (const QJsonValue &v : o.value(QStringLiteral("indexes")).toArray()) {
        const QJsonObject i = v.toObject();
        QiIndexInfo index;
        index.name = i.value(QStringLiteral("name")).toString();
        index.columns = strings(i.value(QStringLiteral("columns")));
        index.unique = i.value(QStringLiteral("unique")).toBool();
        index.implicit = i.value(QStringLiteral("implicit")).toBool();
        t.indexes << index;
    }
    return t;
}

QJsonArray schemaToJson(const QVector<QiTableInfo> &tables)
{
    QJsonArray out;
    for (const QiTableInfo &t : tables)
        out << tableToJson(t);
    return out;
}

QString localPath(const QVariant &fileOrUrl)
{
    const QString text = fileOrUrl.toString();
    return text.startsWith(QLatin1String("file:")) ? QUrl(text).toLocalFile() : text;
}

constexpr int FormatVersion = 1;

} // namespace

QByteArray SchemaDesign::toJson() const
{
    QJsonArray design;
    for (const DesignTable &t : m_tables)
        design << QJsonObject{ { QStringLiteral("table"), tableToJson(t.info) },
                               { QStringLiteral("origin"), t.origin },
                               { QStringLiteral("columnOrigins"), QJsonArray::fromStringList(t.columnOrigins) } };
    const QJsonObject root{
        { QStringLiteral("format"), QStringLiteral("qivot-design") },
        { QStringLiteral("version"), FormatVersion },
        { QStringLiteral("dialect"), m_dialect },
        { QStringLiteral("database"), m_session && m_session->isOpen() ? m_session->displayName() : QString() },
        { QStringLiteral("original"), schemaToJson(m_original) },
        { QStringLiteral("design"), design },
    };
    return QJsonDocument(root).toJson(QJsonDocument::Indented);
}

bool SchemaDesign::fromJson(const QByteArray &json, QString *why)
{
    QJsonParseError parse;
    const QJsonDocument doc = QJsonDocument::fromJson(json, &parse);
    const QJsonObject root = doc.object();
    if (doc.isNull() || root.value(QStringLiteral("format")).toString() != QLatin1String("qivot-design")) {
        if (why)
            *why = doc.isNull() ? parse.errorString() : tr("This isn't a Qivot Studio design.");
        return false;
    }
    if (root.value(QStringLiteral("version")).toInt() > FormatVersion) {
        if (why)
            *why = tr("This design was saved by a newer Qivot Studio.");
        return false;
    }
    QVector<QiTableInfo> original;
    for (const QJsonValue &v : root.value(QStringLiteral("original")).toArray())
        original << tableFromJson(v.toObject());
    QVector<DesignTable> design;
    for (const QJsonValue &v : root.value(QStringLiteral("design")).toArray()) {
        const QJsonObject o = v.toObject();
        DesignTable t;
        t.info = tableFromJson(o.value(QStringLiteral("table")).toObject());
        t.origin = o.value(QStringLiteral("origin")).toString();
        t.columnOrigins = strings(o.value(QStringLiteral("columnOrigins")));
        while (t.columnOrigins.size() < t.info.columns.size())
            t.columnOrigins << QString();
        design << t;
    }
    m_dialect = root.value(QStringLiteral("dialect")).toString(QStringLiteral("sqlite"));
    m_original = original;
    m_tables = design;
    m_undo.clear();
    m_redo.clear();
    return true;
}

bool SchemaDesign::save(const QVariant &fileOrUrl)
{
    QString path = localPath(fileOrUrl);
    if (!path.endsWith(QLatin1String(".qivotdesign")))
        path += QStringLiteral(".qivotdesign");
    QFile file(path);
    if (!file.open(QIODevice::WriteOnly) || file.write(toJson()) < 0) {
        setError(tr("Couldn't save %1: %2").arg(QFileInfo(path).fileName(), file.errorString()));
        return false;
    }
    m_filePath = path;
    setError(QString());
    emit designChanged();
    return true;
}

bool SchemaDesign::load(const QVariant &fileOrUrl)
{
    const QString path = localPath(fileOrUrl);
    QFile file(path);
    if (!file.open(QIODevice::ReadOnly)) {
        setError(tr("Couldn't open %1: %2").arg(QFileInfo(path).fileName(), file.errorString()));
        return false;
    }
    QString why;
    if (!fromJson(file.readAll(), &why)) {
        setError(why);
        return false;
    }
    m_filePath = path;
    m_restored = false;
    // Say so if the database it was designed against has changed since.
    QString note;
    if (m_session && m_session->isOpen()) {
        SchemaDesign now;
        now.reset(m_session->tableInfos(), m_session->dialect());
        if (schemaToJson(now.m_original) != schemaToJson(m_original))
            note = tr("The open database has changed since this design was made; the migration compares "
                      "with the schema saved in the design.");
    }
    setError(note);
    m_loading = true;
    emit designChanged();
    m_loading = false;
    return true;
}

QString SchemaDesign::autosavePath() const
{
    if (!m_session || !m_session->isOpen())
        return QString();
    const QVariantMap s = m_session->connectionSettings();
    const QByteArray key = (s.value(QStringLiteral("type")).toString() + QLatin1Char('|')
                            + s.value(QStringLiteral("path")).toString() + QLatin1Char('|')
                            + s.value(QStringLiteral("host")).toString() + QLatin1Char('|')
                            + s.value(QStringLiteral("port")).toString() + QLatin1Char('|')
                            + s.value(QStringLiteral("database")).toString()).toUtf8();
    const QString dir = QStandardPaths::writableLocation(QStandardPaths::AppDataLocation) + QStringLiteral("/designs");
    return dir + QLatin1Char('/') + QString::fromLatin1(QCryptographicHash::hash(key, QCryptographicHash::Sha1).toHex().left(16))
         + QStringLiteral(".qivotdesign");
}

void SchemaDesign::setAutosaveEnabled(bool on)
{
    if (on == m_autosave)
        return;
    m_autosave = on;
    emit autosaveChanged();
}

void SchemaDesign::autosave()
{
    if (m_loading || !m_autosave)
        return;
    const QString path = autosavePath();
    if (path.isEmpty())
        return;
    if (Migration::changes(m_original, m_tables).isEmpty()) {
        QFile::remove(path);                // nothing worth keeping
        return;
    }
    QDir().mkpath(QFileInfo(path).absolutePath());
    QFile file(path);
    if (file.open(QIODevice::WriteOnly))
        file.write(toJson());
}

bool SchemaDesign::restoreAutosave()
{
    const QString path = m_autosave ? autosavePath() : QString();
    QFile file(path);
    if (path.isEmpty() || !file.open(QIODevice::ReadOnly))
        return false;
    SchemaDesign saved;
    if (!saved.fromJson(file.readAll()))
        return false;
    // Only if it was made against the database as it is now.
    if (schemaToJson(saved.m_original) != schemaToJson(m_original) || saved.m_dialect != m_dialect)
        return false;
    m_tables = saved.m_tables;
    m_restored = true;
    return true;
}

int SchemaDesign::errorCount() const
{
    int n = 0;
    for (const QVariant &p : m_problems)
        n += p.toMap().value(QStringLiteral("severity")).toString() == QLatin1String("error") ? 1 : 0;
    return n;
}

QVariantList SchemaDesign::problemsFor(const QString &table) const
{
    QVariantList out;
    for (const QVariant &p : m_problems)
        if (p.toMap().value(QStringLiteral("table")).toString() == table)
            out << p;
    return out;
}

qint64 SchemaDesign::scalar(const QString &sql) const
{
    if (!m_session || !m_session->isOpen())
        return -1;
    QSqlQuery q(QSqlDatabase::database(m_session->connectionName()));
    if (!q.exec(sql) || !q.next())
        return -1;
    return q.value(0).toLongLong();
}

void SchemaDesign::validate()
{
    QVariantList errors, warnings;
    // `fix`: a one-click way out the UI can offer ("allowEmpty").
    auto add = [&](const QString &severity, const QString &table, const QString &column, const QString &message,
                   const QString &fix = QString()) {
        (severity == QLatin1String("error") ? errors : warnings)
            << QVariantMap{ { QStringLiteral("severity"), severity }, { QStringLiteral("table"), table },
                            { QStringLiteral("column"), column }, { QStringLiteral("message"), message },
                            { QStringLiteral("fix"), fix } };
    };
    auto plural = [](qint64 n, const char *one, const char *many) {
        return QStringLiteral("%1 %2").arg(QLocale().toString(n), QString::fromLatin1(n == 1 ? one : many));
    };
    const bool live = m_session && m_session->isOpen();

    // The C++ generator's notes (names Qivot can't use, no key, ...).
    const CodeGen gen(infos(), m_dialect);
    for (const CodeGen::Model &m : gen.models())
        for (const CodeGen::Warning &w : m.warnings)
            add(QStringLiteral("warning"), m.table, w.column, w.message);

    for (const DesignTable &t : m_tables) {
        const QString name = t.info.name;
        const QiTableInfo *before = nullptr;
        for (const QiTableInfo &o : m_original)
            if (o.name == t.origin)
                before = &o;
        const QString sqlTable = before && live ? m_session->sqlName(before->name) : QString();
        const qint64 rows = before ? scalar(QStringLiteral("SELECT COUNT(*) FROM ") + sqlTable) : 0;

        if (t.info.columns.isEmpty())
            add(QStringLiteral("error"), name, QString(), tr("A table needs at least one column."));

        // References: to a key, and with a type that can hold it.
        for (const QiForeignKeyInfo &fk : t.info.foreignKeys) {
            const DesignTable *target = find(fk.refTable);
            if (!target) {
                add(QStringLiteral("error"), name, fk.columns.join(QStringLiteral(", ")),
                    tr("References %1, which isn't in the design.").arg(fk.refTable));
                continue;
            }
            if (fk.refColumns != target->info.primaryKey)
                add(QStringLiteral("warning"), name, fk.columns.join(QStringLiteral(", ")),
                    tr("References %1 (%2), which isn't its primary key.").arg(fk.refTable, fk.refColumns.join(QStringLiteral(", "))));
            for (int i = 0; i < fk.columns.size() && i < fk.refColumns.size(); ++i) {
                const QiColumnInfo *c = t.info.column(fk.columns.at(i));
                const QiColumnInfo *k = target->info.column(fk.refColumns.at(i));
                if (c && k && CodeGen::cppType(c->type) != CodeGen::cppType(k->type))
                    add(QStringLiteral("error"), name, c->name,
                        tr("Is %1 but references %2.%3, which is %4.").arg(c->type, fk.refTable, k->name, k->type));
            }
        }

        if (!before || rows <= 0)
            continue;               // a new or empty table: nothing in the data to clash with

        // Against the data in the database.
        for (int i = 0; i < t.info.columns.size(); ++i) {
            const QiColumnInfo &c = t.info.columns.at(i);
            const QString origin = t.columnOrigins.value(i);
            const QiColumnInfo *was = origin.isEmpty() ? nullptr : before->column(origin);
            const bool required = !c.nullable && !t.info.primaryKey.contains(c.name);
            if (!was) {
                if (required && defaultOf(c).isEmpty() && !c.autoIncrement) {
                    QString reference;
                    for (const QiForeignKeyInfo &fk : t.info.foreignKeys)
                        if (fk.columns == QStringList{ c.name })
                            reference = fk.refTable;
                    add(QStringLiteral("error"), name, c.name,
                        reference.isEmpty()
                            ? tr("Required, with no default, but %1 already has %2: they'd have no value. "
                                 "Give it a default, or let it be empty.").arg(name, plural(rows, "row", "rows"))
                            : tr("Required, with no default, but %1 already has %2: they'd have no value. "
                                 "Let it be empty for now (fill it in, then make it required), or give it a "
                                 "default that is an existing %3 row.").arg(name, plural(rows, "row", "rows"), reference),
                        QStringLiteral("allowEmpty"));
                } else if (!defaultOf(c).isEmpty()) {
                    // Every existing row gets the default: for a reference it has
                    // to be a row of the referenced table.
                    for (const QiForeignKeyInfo &fk : t.info.foreignKeys) {
                        if (fk.columns != QStringList{ c.name } || fk.refColumns.size() != 1)
                            continue;
                        const DesignTable *target = find(fk.refTable);
                        if (!target)
                            continue;
                        const int keyIndex = columnIndex(target->info, fk.refColumns.first());
                        const QString keyOrigin = keyIndex >= 0 ? target->columnOrigins.value(keyIndex) : QString();
                        const bool exists = !target->origin.isEmpty() && !keyOrigin.isEmpty()
                            && scalar(QStringLiteral("SELECT COUNT(*) FROM %1 WHERE %2 = %3")
                                          .arg(m_session->sqlName(target->origin), Migration::quoted(keyOrigin, m_dialect),
                                               defaultOf(c))) != 0;   // -1: couldn't tell (a function, say)
                        if (!exists)
                            add(QStringLiteral("error"), name, c.name,
                                tr("Defaults to %1, but %2 has no row %1%3: all %4 would point at nothing. "
                                   "Let it be empty for now (fill it in, then make it required).")
                                    .arg(defaultOf(c), fk.refTable,
                                         target->origin.isEmpty() ? tr(" (it's a new, empty table)") : QString(),
                                         plural(rows, "row", "rows")),
                                QStringLiteral("allowEmpty"));
                    }
                }
                continue;
            }
            const QString col = Migration::quoted(origin, m_dialect);
            if (required && was->nullable) {
                const qint64 nulls = scalar(QStringLiteral("SELECT COUNT(*) FROM %1 WHERE %2 IS NULL").arg(sqlTable, col));
                if (nulls > 0)
                    add(QStringLiteral("error"), name, c.name,
                        tr("Required, but %1 have no value.").arg(plural(nulls, "row", "rows")), QStringLiteral("allowEmpty"));
            }
            if (isUnique(t.info, c.name) && !isUnique(*before, origin) && t.info.primaryKey != QStringList{ c.name }) {
                const qint64 dupes = scalar(QStringLiteral("SELECT COUNT(%2) - COUNT(DISTINCT %2) FROM %1").arg(sqlTable, col));
                if (dupes > 0)
                    add(QStringLiteral("error"), name, c.name,
                        tr("Unique, but %1 repeat an earlier value.").arg(plural(dupes, "row", "rows")));
            }
            if (c.type.trimmed().compare(was->type.trimmed(), Qt::CaseInsensitive) != 0
                && CodeGen::cppType(c.type) != CodeGen::cppType(was->type))
                add(QStringLiteral("warning"), name, c.name,
                    tr("Changes from %1 to %2: values that don't convert may be lost or refused.").arg(was->type, c.type));
        }

        // New references on existing columns to existing tables: values that point nowhere.
        for (const QiForeignKeyInfo &fk : t.info.foreignKeys) {
            if (fk.columns.size() != 1)
                continue;
            const int index = columnIndex(t.info, fk.columns.first());
            const QString origin = index >= 0 ? t.columnOrigins.value(index) : QString();
            const DesignTable *target = find(fk.refTable);
            if (origin.isEmpty() || !target || target->origin.isEmpty() || fk.refColumns.size() != 1)
                continue;
            bool existed = false;
            for (const QiForeignKeyInfo &old : before->foreignKeys)
                existed = existed || (old.columns == QStringList{ origin } && old.refTable == target->origin);
            const int keyIndex = columnIndex(target->info, fk.refColumns.first());
            const QString keyOrigin = keyIndex >= 0 ? target->columnOrigins.value(keyIndex) : QString();
            if (existed || keyOrigin.isEmpty())
                continue;
            const QString col = Migration::quoted(origin, m_dialect);
            const qint64 orphans = scalar(QStringLiteral("SELECT COUNT(*) FROM %1 WHERE %2 IS NOT NULL AND %2 NOT IN (SELECT %3 FROM %4)")
                                              .arg(sqlTable, col, Migration::quoted(keyOrigin, m_dialect),
                                                   m_session->sqlName(target->origin)));
            if (orphans > 0)
                add(QStringLiteral("error"), name, fk.columns.first(),
                    tr("%1 point at no %2 row.").arg(plural(orphans, "row", "rows"), fk.refTable));
        }

        // What goes away with dropped columns.
        for (const QiColumnInfo &c : before->columns)
            if (!t.columnOrigins.contains(c.name))
                add(QStringLiteral("warning"), name, c.name,
                    tr("Dropped, with its values in %1.").arg(plural(rows, "row", "rows")));
    }
    for (const QiTableInfo &o : m_original) {
        bool kept = false;
        for (const DesignTable &t : m_tables)
            kept = kept || t.origin == o.name;
        if (!kept) {
            const qint64 rows = live ? scalar(QStringLiteral("SELECT COUNT(*) FROM ") + m_session->sqlName(o.name)) : 0;
            if (rows > 0)
                add(QStringLiteral("warning"), o.name, QString(),
                    tr("Dropped, with its %1.").arg(plural(rows, "row", "rows")));
        }
    }

    m_problems = errors + warnings;
    emit problemsChanged();
}

void SchemaDesign::setSession(DatabaseSession *session)
{
    if (session == m_session)
        return;
    if (m_session)
        disconnect(m_session, nullptr, this, nullptr);
    m_session = session;
    if (m_session)
        connect(m_session, &DatabaseSession::openChanged, this, [this] { openSession(); });
    emit sessionChanged();
    openSession();
}

void SchemaDesign::reset()
{
    if (m_session && m_session->isOpen())
        reset(m_session->tableInfos(), m_session->dialect());
    else
        reset({}, QStringLiteral("sqlite"));
}

void SchemaDesign::discard()
{
    const QString path = autosavePath();
    if (!path.isEmpty())
        QFile::remove(path);
    m_filePath.clear();
    reset();
}

void SchemaDesign::openSession()
{
    m_loading = true;                       // don't autosave the database's own state over the saved design
    reset();
    m_loading = false;
    if (restoreAutosave()) {
        m_loading = true;
        emit designChanged();
        m_loading = false;
    }
}

void SchemaDesign::reset(const QVector<QiTableInfo> &original, const QString &dialect)
{
    m_dialect = dialect;
    m_original.clear();
    m_tables.clear();
    for (QiTableInfo t : original) {
        if (t.kind != QiTableInfo::Table)
            continue;
        // Defaults as SQL text, the same on both sides of the comparison.
        for (QiColumnInfo &c : t.columns) {
            const QString d = CodeGen::defaultExpression(c.defaultValue, dialect);
            c.defaultValue = d.isEmpty() || c.autoIncrement ? QVariant() : QVariant(d);
        }
        m_original << t;
        DesignTable d;
        d.info = t;
        d.origin = t.name;
        for (const QiColumnInfo &c : t.columns)
            d.columnOrigins << c.name;
        m_tables << d;
    }
    m_undo.clear();
    m_redo.clear();
    m_restored = false;
    m_filePath.clear();
    setError(QString());
    emit designChanged();
}

QVariantList SchemaDesign::tables() const
{
    QVariantList out;
    for (const DesignTable &t : m_tables)
        out << QVariantMap{ { QStringLiteral("name"), t.info.name },
                            { QStringLiteral("isNew"), t.origin.isEmpty() },
                            { QStringLiteral("columns"), t.info.columns.size() } };
    return out;
}

QStringList SchemaDesign::typeSuggestions() const
{
    if (m_dialect == QLatin1String("postgres"))
        return { QStringLiteral("integer"), QStringLiteral("bigint"), QStringLiteral("text"), QStringLiteral("varchar(255)"),
                 QStringLiteral("numeric(10,2)"), QStringLiteral("double precision"), QStringLiteral("boolean"),
                 QStringLiteral("date"), QStringLiteral("timestamp"), QStringLiteral("time"), QStringLiteral("bytea"),
                 QStringLiteral("uuid"), QStringLiteral("jsonb") };
    if (m_dialect == QLatin1String("mysql"))
        return { QStringLiteral("INT"), QStringLiteral("BIGINT"), QStringLiteral("VARCHAR(255)"), QStringLiteral("TEXT"),
                 QStringLiteral("DECIMAL(10,2)"), QStringLiteral("DOUBLE"), QStringLiteral("TINYINT(1)"),
                 QStringLiteral("DATE"), QStringLiteral("DATETIME"), QStringLiteral("TIME"), QStringLiteral("BLOB"),
                 QStringLiteral("JSON") };
    if (m_dialect == QLatin1String("sqlserver"))
        return { QStringLiteral("INT"), QStringLiteral("BIGINT"), QStringLiteral("NVARCHAR(255)"), QStringLiteral("NVARCHAR(MAX)"),
                 QStringLiteral("DECIMAL(10,2)"), QStringLiteral("FLOAT"), QStringLiteral("BIT"), QStringLiteral("DATE"),
                 QStringLiteral("DATETIME2"), QStringLiteral("TIME"), QStringLiteral("VARBINARY(MAX)") };
    return { QStringLiteral("INTEGER"), QStringLiteral("TEXT"), QStringLiteral("REAL"), QStringLiteral("NUMERIC"),
             QStringLiteral("BOOLEAN"), QStringLiteral("DATE"), QStringLiteral("DATETIME"), QStringLiteral("BLOB") };
}

DesignTable *SchemaDesign::find(const QString &name)
{
    for (DesignTable &t : m_tables)
        if (t.info.name == name)
            return &t;
    return nullptr;
}

const DesignTable *SchemaDesign::find(const QString &name) const
{
    for (const DesignTable &t : m_tables)
        if (t.info.name == name)
            return &t;
    return nullptr;
}

QString SchemaDesign::uniqueTableName(const QString &base) const
{
    QString name = base;
    for (int n = 2; find(name); ++n)
        name = base + QString::number(n);
    return name;
}

void SchemaDesign::edit()
{
    m_restored = false;
    m_undo << m_tables;
    if (m_undo.size() > 200)
        m_undo.removeFirst();
    m_redo.clear();
}

void SchemaDesign::setError(const QString &error)
{
    if (error == m_error)
        return;
    m_error = error;
    emit errorChanged();
}

QVariantMap SchemaDesign::table(const QString &name) const
{
    const DesignTable *t = find(name);
    if (!t)
        return {};
    QVariantList columns;
    for (int i = 0; i < t->info.columns.size(); ++i) {
        const QiColumnInfo &c = t->info.columns.at(i);
        QString reference, onDelete;
        for (const QiForeignKeyInfo &fk : t->info.foreignKeys)
            if (fk.columns == QStringList{ c.name }) {
                reference = fk.refTable;
                onDelete = fk.onDelete;
            }
        columns << QVariantMap{
            { QStringLiteral("name"), c.name },
            { QStringLiteral("type"), c.type },
            { QStringLiteral("nullable"), c.nullable },
            { QStringLiteral("primaryKey"), t->info.primaryKey.contains(c.name) },
            { QStringLiteral("autoIncrement"), c.autoIncrement },
            { QStringLiteral("unique"), isUnique(t->info, c.name) },
            { QStringLiteral("defaultValue"), defaultOf(c) },
            { QStringLiteral("reference"), reference },
            { QStringLiteral("onDelete"), onDelete },
            { QStringLiteral("isNew"), t->columnOrigins.value(i).isEmpty() },
        };
    }
    QStringList referencedBy;
    for (const DesignTable &other : m_tables)
        for (const QiForeignKeyInfo &fk : other.info.foreignKeys)
            if (fk.refTable == name && !referencedBy.contains(other.info.name))
                referencedBy << other.info.name;
    return { { QStringLiteral("name"), t->info.name },
             { QStringLiteral("isNew"), t->origin.isEmpty() },
             { QStringLiteral("origin"), t->origin },
             { QStringLiteral("columns"), columns },
             { QStringLiteral("referencedBy"), referencedBy } };
}

QString SchemaDesign::addTable(const QString &requested)
{
    edit();
    DesignTable t;
    t.info.name = uniqueTableName(requested.trimmed().isEmpty() ? QStringLiteral("new_table") : requested.trimmed());
    QiColumnInfo id;
    id.name = QStringLiteral("id");
    id.type = typeSuggestions().first();
    id.nullable = false;
    id.primaryKey = true;
    id.primaryKeyOrder = 1;
    id.autoIncrement = true;
    t.info.columns << id;
    t.info.primaryKey << id.name;
    t.columnOrigins << QString();
    m_tables << t;
    emit designChanged();
    return t.info.name;
}

bool SchemaDesign::renameTable(const QString &name, const QString &newName)
{
    const QString to = newName.trimmed();
    DesignTable *t = find(name);
    if (!t || to.isEmpty() || to == name)
        return false;
    if (find(to)) {
        setError(tr("There's already a table called %1.").arg(to));
        return false;
    }
    edit();
    t = find(name);
    t->info.name = to;
    for (DesignTable &other : m_tables)
        for (QiForeignKeyInfo &fk : other.info.foreignKeys)
            if (fk.refTable == name)
                fk.refTable = to;
    setError(QString());
    emit designChanged();
    return true;
}

void SchemaDesign::removeTable(const QString &name)
{
    if (!find(name))
        return;
    edit();
    for (int i = 0; i < m_tables.size(); ++i)
        if (m_tables[i].info.name == name)
            m_tables.removeAt(i--);
    for (DesignTable &other : m_tables)
        for (int i = 0; i < other.info.foreignKeys.size(); ++i)
            if (other.info.foreignKeys[i].refTable == name)
                other.info.foreignKeys.removeAt(i--);
    emit designChanged();
}

QString SchemaDesign::addColumn(const QString &table, const QString &requested, const QString &type)
{
    if (!find(table))
        return QString();
    edit();
    DesignTable *t = find(table);
    const QString base = requested.trimmed().isEmpty() ? QStringLiteral("new_column") : requested.trimmed();
    QString name = base;
    for (int n = 2; t->info.column(name); ++n)
        name = base + QString::number(n);
    QiColumnInfo c;
    c.name = name;
    c.type = type.isEmpty() ? typeSuggestions().value(1) : type;
    t->info.columns << c;
    t->columnOrigins << QString();
    emit designChanged();
    return name;
}

bool SchemaDesign::updateColumn(const QString &table, int index, const QVariantMap &changes)
{
    const DesignTable *current = find(table);
    if (!current || index < 0 || index >= current->info.columns.size())
        return false;
    const QString oldName = current->info.columns.at(index).name;
    if (changes.contains(QStringLiteral("name"))) {
        const QString newName = changes.value(QStringLiteral("name")).toString().trimmed();
        if (newName.isEmpty())
            return false;
        if (newName != oldName && current->info.column(newName)) {
            setError(tr("%1 already has a column called %2.").arg(table, newName));
            return false;
        }
    }
    edit();
    DesignTable *t = find(table);
    QiColumnInfo &c = t->info.columns[index];

    if (changes.contains(QStringLiteral("name"))) {
        const QString newName = changes.value(QStringLiteral("name")).toString().trimmed();
        c.name = newName;
        for (QString &k : t->info.primaryKey)
            if (k == oldName) k = newName;
        for (QiForeignKeyInfo &fk : t->info.foreignKeys)
            for (QString &k : fk.columns)
                if (k == oldName) k = newName;
        for (QiIndexInfo &i : t->info.indexes)
            for (QString &k : i.columns)
                if (k == oldName) k = newName;
        for (DesignTable &other : m_tables)            // references to this column
            for (QiForeignKeyInfo &fk : other.info.foreignKeys)
                if (fk.refTable == table)
                    for (QString &k : fk.refColumns)
                        if (k == oldName) k = newName;
    }
    if (changes.contains(QStringLiteral("type")))
        c.type = changes.value(QStringLiteral("type")).toString().trimmed();
    if (changes.contains(QStringLiteral("nullable")))
        c.nullable = changes.value(QStringLiteral("nullable")).toBool();
    if (changes.contains(QStringLiteral("defaultValue"))) {
        const QString d = changes.value(QStringLiteral("defaultValue")).toString().trimmed();
        c.defaultValue = d.isEmpty() ? QVariant() : QVariant(d);
    }
    if (changes.contains(QStringLiteral("primaryKey"))) {
        const bool key = changes.value(QStringLiteral("primaryKey")).toBool();
        t->info.primaryKey.removeAll(c.name);
        if (key) {
            // Keep the key in column order.
            QStringList ordered;
            for (const QiColumnInfo &col : t->info.columns)
                if (col.name == c.name || t->info.primaryKey.contains(col.name))
                    ordered << col.name;
            t->info.primaryKey = ordered;
            c.nullable = false;
        } else {
            c.autoIncrement = false;
        }
        for (int i = 0; i < t->info.columns.size(); ++i) {
            t->info.columns[i].primaryKey = t->info.primaryKey.contains(t->info.columns[i].name);
            t->info.columns[i].primaryKeyOrder = t->info.primaryKey.indexOf(t->info.columns[i].name) + 1;
            if (t->info.primaryKey.size() > 1)
                t->info.columns[i].autoIncrement = false;
        }
    }
    if (changes.contains(QStringLiteral("unique"))) {
        const bool unique = changes.value(QStringLiteral("unique")).toBool();
        for (int i = 0; i < t->info.indexes.size(); ++i)
            if (t->info.indexes[i].unique && t->info.indexes[i].columns == QStringList{ c.name })
                t->info.indexes.removeAt(i--);
        if (unique) {
            QiIndexInfo index;
            index.columns << c.name;
            index.unique = true;
            index.implicit = true;
            t->info.indexes << index;
        }
    }
    setError(QString());
    emit designChanged();
    return true;
}

void SchemaDesign::removeColumn(const QString &table, int index)
{
    const DesignTable *current = find(table);
    if (!current || index < 0 || index >= current->info.columns.size())
        return;
    edit();
    DesignTable *t = find(table);
    const QString name = t->info.columns.at(index).name;
    t->info.columns.removeAt(index);
    t->columnOrigins.removeAt(index);
    t->info.primaryKey.removeAll(name);
    for (int i = 0; i < t->info.foreignKeys.size(); ++i)
        if (t->info.foreignKeys[i].columns.contains(name))
            t->info.foreignKeys.removeAt(i--);
    for (int i = 0; i < t->info.indexes.size(); ++i)
        if (t->info.indexes[i].columns.contains(name))
            t->info.indexes.removeAt(i--);
    for (DesignTable &other : m_tables)
        for (int i = 0; i < other.info.foreignKeys.size(); ++i)
            if (other.info.foreignKeys[i].refTable == table && other.info.foreignKeys[i].refColumns.contains(name))
                other.info.foreignKeys.removeAt(i--);
    emit designChanged();
}

void SchemaDesign::moveColumn(const QString &table, int from, int to)
{
    const DesignTable *current = find(table);
    if (!current || from == to || from < 0 || to < 0 || from >= current->info.columns.size()
        || to >= current->info.columns.size())
        return;
    edit();
    DesignTable *t = find(table);
    t->info.columns.move(from, to);
    t->columnOrigins.move(from, to);
    emit designChanged();
}

bool SchemaDesign::setReference(const QString &table, const QString &column, const QString &refTable,
                                const QString &onDelete)
{
    const DesignTable *current = find(table);
    if (!current || !current->info.column(column))
        return false;
    const DesignTable *target = refTable.isEmpty() ? nullptr : find(refTable);
    if (!refTable.isEmpty() && (!target || target->info.primaryKey.size() != 1)) {
        setError(tr("%1 needs a single-column primary key to be referenced.").arg(refTable));
        return false;
    }
    edit();
    DesignTable *t = find(table);
    for (int i = 0; i < t->info.foreignKeys.size(); ++i)
        if (t->info.foreignKeys[i].columns == QStringList{ column })
            t->info.foreignKeys.removeAt(i--);
    if (target) {
        QiForeignKeyInfo fk;
        fk.columns << column;
        fk.refTable = refTable;
        fk.refColumns = target->info.primaryKey;
        fk.onDelete = onDelete;
        t->info.foreignKeys << fk;
        // The column takes the key's type, so the reference can hold it.
        const QiColumnInfo *key = target->info.column(target->info.primaryKey.first());
        QiColumnInfo *c = nullptr;
        for (QiColumnInfo &col : t->info.columns)
            if (col.name == column)
                c = &col;
        if (key && c && CodeGen::cppType(c->type) != CodeGen::cppType(key->type))
            c->type = key->type.contains(QLatin1String("serial"), Qt::CaseInsensitive) ? QStringLiteral("integer") : key->type;
    }
    setError(QString());
    emit designChanged();
    return true;
}

QString SchemaDesign::addReference(const QString &table, const QString &refTable, const QString &onDelete)
{
    const DesignTable *t = find(table);
    const DesignTable *target = find(refTable);
    if (!t || !target || target->info.primaryKey.size() != 1) {
        setError(tr("%1 needs a single-column primary key to be referenced.").arg(refTable));
        return QString();
    }
    const QString key = target->info.primaryKey.first();
    const QString bare = bareName(refTable);
    // book -> category: "category_id"; to a key already named category_id: "category_id".
    const QString base = key.startsWith(bare, Qt::CaseInsensitive) ? key : bare + QLatin1Char('_') + key;
    QString name = base;
    for (int n = 2; t->info.column(name); ++n)
        name = base + QString::number(n);

    // One undo step for the column and its reference together.
    const QiColumnInfo *k = target->info.column(key);
    edit();
    DesignTable *mine = find(table);
    QiColumnInfo c;
    c.name = name;
    c.type = k && k->type.contains(QLatin1String("serial"), Qt::CaseInsensitive) ? QStringLiteral("integer")
           : k ? k->type : typeSuggestions().first();
    mine->info.columns << c;
    mine->columnOrigins << QString();
    QiForeignKeyInfo fk;
    fk.columns << name;
    fk.refTable = refTable;
    fk.refColumns << key;
    fk.onDelete = onDelete;
    mine->info.foreignKeys << fk;
    setError(QString());
    emit designChanged();
    return name;
}

bool SchemaDesign::setOnDelete(const QString &table, const QString &column, const QString &onDelete)
{
    const DesignTable *t = find(table);
    if (!t)
        return false;
    int index = -1;
    for (int i = 0; i < t->info.foreignKeys.size(); ++i)
        if (t->info.foreignKeys.at(i).columns == QStringList{ column })
            index = i;
    if (index < 0 || t->info.foreignKeys.at(index).onDelete == onDelete)
        return false;
    edit();
    find(table)->info.foreignKeys[index].onDelete = onDelete;
    emit designChanged();
    return true;
}

void SchemaDesign::undo()
{
    if (m_undo.isEmpty())
        return;
    m_redo << m_tables;
    m_tables = m_undo.takeLast();
    emit designChanged();
}

void SchemaDesign::redo()
{
    if (m_redo.isEmpty())
        return;
    m_undo << m_tables;
    m_tables = m_redo.takeLast();
    emit designChanged();
}

QVector<QiTableInfo> SchemaDesign::infos() const
{
    QVector<QiTableInfo> out;
    for (const DesignTable &t : m_tables)
        out << t.info;
    return out;
}

QVariantMap SchemaDesign::diagram() const
{
    // The cards say which tables are new or edited.
    QVariantMap d = DiagramData::build(infos(), {});
    const QStringList changed = Migration::changedTables(m_original, m_tables);
    QVariantList tables = d.value(QStringLiteral("tables")).toList();
    for (QVariant &v : tables) {
        QVariantMap t = v.toMap();
        const DesignTable *dt = find(t.value(QStringLiteral("name")).toString());
        QStringList errors;
        for (const QVariant &v : problemsFor(t.value(QStringLiteral("name")).toString())) {
            const QVariantMap p = v.toMap();
            if (p.value(QStringLiteral("severity")).toString() == QLatin1String("error"))
                errors << (p.value(QStringLiteral("column")).toString().isEmpty()
                               ? p.value(QStringLiteral("message")).toString()
                               : p.value(QStringLiteral("column")).toString() + QStringLiteral(": ")
                                     + p.value(QStringLiteral("message")).toString());
        }
        const bool broken = !errors.isEmpty();
        t.insert(QStringLiteral("errors"), errors);
        t.insert(QStringLiteral("status"), broken ? QStringLiteral("error")
                                         : dt && dt->origin.isEmpty() ? QStringLiteral("new")
                                         : changed.contains(t.value(QStringLiteral("name")).toString()) ? QStringLiteral("changed")
                                         : QString());
        v = t;
    }
    d.insert(QStringLiteral("tables"), tables);
    return d;
}

QVariantMap SchemaDesign::cppModel(const QString &table) const
{
    const CodeGen::Model m = CodeGen(infos(), m_dialect).model(table);
    if (!m.isValid())
        return {};
    QVariantList warnings;
    for (const CodeGen::Warning &w : m.warnings)
        warnings << QVariantMap{ { QStringLiteral("column"), w.column }, { QStringLiteral("message"), w.message } };
    return { { QStringLiteral("className"), m.className },
             { QStringLiteral("code"), m.code },
             { QStringLiteral("warnings"), warnings } };
}

QString SchemaDesign::cppHeader() const
{
    return CodeGen(infos(), m_dialect).header();
}

QString SchemaDesign::applyToCopy()
{
    if (m_dialect != QLatin1String("sqlite") || !m_session || m_session->filePath().isEmpty()) {
        setError(tr("Applying to a copy works for SQLite files; copy the SQL for a server."));
        return QString();
    }
    const QFileInfo source(m_session->filePath());
    QString target;
    for (int n = 1; target.isEmpty() || QFileInfo::exists(target); ++n)
        target = source.dir().filePath(QStringLiteral("%1-designed%2.%3")
                                           .arg(source.completeBaseName(), n > 1 ? QString::number(n) : QString(),
                                                source.suffix().isEmpty() ? QStringLiteral("db") : source.suffix()));
    if (!QFile::copy(source.absoluteFilePath(), target)) {
        setError(tr("Couldn't copy %1.").arg(source.fileName()));
        return QString();
    }
    const QString script = migration();
    const QString connection = QStringLiteral("design-") + QUuid::createUuid().toString(QUuid::WithoutBraces);
    QString failure;
    {
        QSqlDatabase db = QSqlDatabase::addDatabase(QStringLiteral("QSQLITE"), connection);
        db.setDatabaseName(target);
        if (!db.open()) {
            failure = db.lastError().text();
        } else {
            // One statement at a time (QSqlQuery runs one); comments dropped first.
            QString text;
            for (const QString &line : script.split(QLatin1Char('\n')))
                if (!line.trimmed().startsWith(QLatin1String("--")))
                    text += line + QLatin1Char('\n');
            QSqlQuery q(db);
            for (const QString &statement : text.split(QLatin1Char(';'))) {
                if (statement.trimmed().isEmpty())
                    continue;
                if (!q.exec(statement)) {
                    failure = QStringLiteral("%1\n%2").arg(q.lastError().text(), statement.trimmed());
                    q.exec(QStringLiteral("ROLLBACK"));
                    break;
                }
            }
            db.close();
        }
    }
    QSqlDatabase::removeDatabase(connection);
    if (!failure.isEmpty()) {
        QFile::remove(target);
        setError(tr("The migration failed on the copy: %1").arg(failure));
        return QString();
    }
    setError(QString());
    return target;
}
